nats-io/nats-streaming-server

server/server.go

The queue state object needs to be locked when removing a subscriber
from the list.

Fix data race on client close

---

server/server.go
server/server_test.go

When a durable is restarted, we need to force the delivery, even
if the number of pending acks is greater or equal to the current
MaxInFlight, otherwise, the durable would not receive messages
until after multiple failed redeliveries.
Resolves #117

Fix durable restart when ack pending >= MaxInFlight

---

server/server.go

Default options are already configured to allow reconnect, etc...
Using the empty Options like we did would have prevented the server
to reconnect should its connection to the NATS Server be disconnected
(like in the case of a slow consumer error).

Use NATS default options when server creates connection to NATS Server

---

nats-streaming-server.go
server/client_test.go
server/server.go
server/server_test.go
stores/common.go
stores/common_test.go
stores/filestore.go
stores/filestore_test.go
stores/memstore_test.go
stores/store.go

Originally submitted by Colin: https://github.com/nats-io/nats-streaming-server/pull/119
- Uses a channel to pass messages to an IO thread
- Uses bufio to flush data to disk (Message and Subscriptions stores)
- fsyncs after a bufio flush to guarantee data

Performance Improvements

---

nats-streaming-server.go
server/client_test.go
server/server.go
spb/protocol.pb.go
spb/protocol.proto
stores/bench_test.go
stores/common.go
stores/filestore.go
stores/filestore_test.go
stores/store.go
util/util.go
util/util_test.go

- Converted Clients file to use protobuf
- Each record has now a CRC-32 checksum field
- Ability to disable CRC check for reads (only occur on startup atm)

Add CRC checksum for file store

---

nats-streaming-server.go
server/server.go
server/server_test.go

By default, the Streaming server embeds the NATS Server.
You can now pass "-embed=false" to connect to an external server.
Still use "-p" or "-a" if needed to connect to the NATS Server.
/cc @ColinSullivan1 @aricart @derekcollison

Add param option to connect to external NATS Server

---

nats-streaming-server.go
stores/filestore.go
stores/filestore_test.go

Using `-file_sync=false` will disable fsync during Flush().
Resolves #127

[ADDED] Ability to enable/disable file sync during Flush()

---

stores/filestore_test.go

The total number of messages was too high when running on Travis.
Cost of fsync there appear to be significant.
Related to PR #128

[CHANGED] File sync test to run faster on Travis

---

nats-streaming-server.go
server/server.go
server/server_test.go

You can now use `-nats_server <url>` instead. When you provide
the url to connect to a NATS server that requires authentication,
you can pass the username and password in the url itself, or
with `-user` and `-pass`. If username and password is present
in the url, they will override the one passed through the
command line.
This PR is related to #125

[CHANGED] Option parameter to connect to external NATS Server

---

README.md

I believe that this is the correct link. The current one returns 404 for me.
Any plans or estimates for a Node.js client release? If it's just around the corner I wont bother hacking my own because of the lack of time to do it properly.

Fix NATS Streaming Quickstart link [ci skip]

---

nats-streaming-server.go

Allow `-ns` as a shortcut
Resolves #133

[ADDED] Shortcut for nats_server command line parameter [ci skip]

---

Dockerfile

This is a first step in getting a Docker image for NATS Streaming.
A repo will soon be created to generate the official image.

[ADDED] Dockerfile [ci skip]

---

server/server.go

The error handler was set twice and the reconnect handler was missing.

[ADDED] Reconnect handler

---

server/server.go
server/server_test.go

When a durable was stopped and restarted, everything would be fine.
However, if durable was stopped, then the server restarted (applies
only to server with file store - since with memory based stores,
no state is recovered), when the durable was once again started,
it would get the error: "stan: duplicate durable registration".
This was because the ClientID, which was recovered from the
subscription info, was not cleared from memory, preventing the
durable to restart.

Fixed some issues with durables

---

server/server.go
stores/filestore.go
stores/filestore_test.go

There were two issues:
- FileStore was storing a reference to the server's SubState object,
which was wrong.
- During a compact, the subscription record was written but LastSent
was potentially wrong. Make sure the store keeps track of the
lastSent when adding a pending message to a given subscription.
Resolves #154

[FIXED] Server losing track of last sent after compact

---

server/server.go
server/server_test.go

Even without call to Unsubscribe() a non durable subscription should
be removed from the store when its connection is closed.
Resolves #159

[FIXED] Remove non durable subscription from store on connection close

---

server/server.go
server/server_test.go
spb/protocol.pb.go
spb/protocol.proto

- You can now create a durable Queue Subscriber using the DurableName()
option in the QueueSubscribe() call.
- For durable queue subscribers, QueueSubscribe() will return an error
if DurableName() contains a name with the ':' character.
- Queue groups with same name can coexist as durable and non durable.
- When creating a subscriber (durable or queue subscriber), the start
position is ignored for queue groups and existing durable subscribers.
Delivery will resume from last sent.
Resolves #156

[ADDED] Durable Queue Subscribers

---

README.md
nats-streaming-server.go
scripts/cov.sh
server/conf.go
server/conf_test.go
server/log_test.go
server/server.go
server/server_test.go
stores/bench_test.go
stores/common.go
stores/common_test.go
stores/filestore.go
stores/filestore_test.go
stores/limits.go
stores/limits_test.go
stores/memstore.go
stores/memstore_test.go
stores/store.go
test/configs/test_parse.conf

Many commits that mainly:
- Add FileStore indexing so that messages are recovered from an index file (avoiding need to recover whole messages)
- Ability to disable caching for file stores
- Buffered writers for SubStore and MsgStore can now shrink to reduce memory need
- Allow MaxMsgs/MaxBytes to be set to 0 to mean "no limit"
- Some improvements (reduced number of memory allocations in processing incoming messages)

Many changes for next release

---

server/server.go

Using two connections can theoretically introduce a protocol ordering issue, particularly when subscription responses are published on a different connection than the messages sent to subscribers.
Imagine the following case where a client makes a subscription request.  The NATS streaming server receives this request, and sends a response on the "general" connection, then starts streaming messages on the "send" connection to a subscriber.  The NATS server happens to service the "send" connection first and sends a `MsgProto` to the subscribing client before the `SubscriptionResponse`.  This violates the protocol and results in undefined behavior at the client.
To mitigate this, send any subscription responses on the "send" connection.  It makes sense to be congruent and do the same with …

Use the send connection to send protocol responses

---

README.md
nats-streaming-server.go
server/conf.go
server/conf_test.go
server/server.go
server/server_test.go
stores/common_test.go
stores/filestore.go
stores/filestore_test.go
test/configs/test_parse.conf

You can now configure file slices to be of a certain size. The channel
limits may still override the size of the slices.
When a file slice is supposed to be removed, if a script has been
defined, the script is invoked with the renamed file slice. The
script can then move those files for archiving.
Related to #192

[ADDED] File slices configuration, including script for archiving

---

server/server.go
stores/filestore.go
stores/memstore.go

When the expiration timer fires, messages that have expired are
removed. The timer is then reset to the first message yet to expire
based on the message’s time left to reach the target expiration
time. A bug was reseting the timer to a negative value, which Go
would translate to setting the timer to a nano-second.

[FIXED] Expiration timer runaway when some but not all messages expire

---

server/server.go
server/server_test.go

When a consumer was stalled (number of ack pending is >= of MaxInflight)
when a redelivery occurred, the server would be prevented from sending
messages since the number of outstanding acks was already at the limit.
Some code was introduced to force redelivery after a certain number
of failed attempts. This code is now removed and redelivery always
resend messages for which acks have not been received.
This helps with message ordering on server or durable restart.
Resolves #187

[CHANGED] Redelivery is now always forced

---

server/server.go
server/server_test.go
spb/protocol.pb.go
spb/protocol.proto

Client can now close a subscription without calling Unsubscribe()
which was a problem for durable subscriptions. Clients were forced
to close the connection if they wanted to stop consuming but not
delete the subscription.
Resolves #182

[ADDED] Support for Subscription.Close()

---

nats-streaming-server.go
server/server_test.go
stores/filestore_test.go

This is a port of PR for NATS Server: https://github.com/nats-io/gnatsd/pull/393
Also fixed some data race and flapping tests.

[FIXED] Prevent unrecognized sub commands in command line

---

server/bench_test.go
server/log_test.go
server/server.go
server/server_test.go
spb/protocol.pb.go
spb/protocol.proto

Commit 66db13cce9be51130c3295002fdb577c41b1a504 had a performance impact in some cases.
For instance, running the server like this:
```
nats-streaming-server -store file -dir datastore
```
and then using the bench tool:
```
go run examples/stan-bench.go -np 1 -ns 10 -n 100000 -a foo
```
produced the following results:
```
Starting benchmark [msgs=100000, msgsize=128, pubs=1, subs=10]
NATS Streaming Pub/Sub stats: 211,574 msgs/sec ~ 25.83 MB/sec
Pub stats: 19,287 msgs/sec ~ 2.35 MB/sec
Sub stats: 192,340 msgs/sec ~ 23.48 MB/sec
```
With this PR, the performance is back while solving the ordering issue:
```
Starting benchmark [msgs=100000, msgsize=128, pubs=1, subs=10]
NATS Streaming Pub/Sub stats: 486,028 msgs/sec ~ 59.33 MB/sec
Pub stats: 44,236 msgs/sec ~ 5.40 MB/sec
Sub stats: 441,870 …
```

Protocol ordering v2

---

server/server.go
vendor/github.com/nats-io/gnatsd/server/route.go
vendor/github.com/nats-io/gnatsd/server/server.go
vendor/github.com/nats-io/gnatsd/test/test.go
vendor/manifest

The NATS Server's "RunServer" functions no longer use GetListenEndpoint().
This function has been removed. When server is embedded, since we
know it is local, use 127.0.0.1 or ::1 if NATS server's host
is 0.0.0.0 or :: respectively.

Update vendor due to removal of GetListenEndpoint()

---

.travis.yml
server/server.go

-Bump version
-Replace after_script with after_success to start coverage or
create release and upload assets only on build success.

Release v0.3.4

---

server/server.go

The methods: performDurableRedelivery() and performAckExpirationRedelivery()
may be called even if there is no message to be redelivered.
Ensure that we print the debug statement only when there is at least
1 message to redeliver.

Print debug redelivery statement only when needed

---

.travis.yml

If we were to introduce 1.8 in the matrix, the coverage/cross
compile would be triggered for both 1.7 and 1.8.
Changing the trigger to only 1.7.x Go version for now.

Change coverage/cross compile trigger for travis.yml

---

stores/common.go
stores/common_test.go
stores/filestore.go
stores/memstore.go
stores/memstore_test.go
util/no_race.go
util/race.go

Since we use `time.Now()` and this is returning the "wall clock",
it is subject to jump both forward or backwards, either due to
user changing the time, NTP, or leap second.
There is no much we can do, but at least we ensure that the messages
in a given log have their timestamp increasing monotonically.
That is, if M1 is stored before M2, then:
```
M1.Sequence<M2.Sequence && M1.Timestamp <= M2.Timestamp
```
The expiration code also now accounts for possible negative delta
between "now" and a given message timestamp.
In part addresses: #231

[FIXED] Ensure message timestamp increases monotonically

---

server/client.go
server/server.go

This allows to have quick access to client's failed hb status when
trying to redeliver messages.

On server-to-client heartbeat, push failed hb status down to subscribers

---

stores/common_test.go
stores/filestore.go
stores/filestore_test.go
stores/memstore.go
util/util.go
util/util_test.go

By not keeping `msgIndex` (which contains message's offset on
data file, timestamp and message size), the memory footprint
is now reduced and actually does not increase for a given
message store, regardless of the number of messages stored.
This causes however to access the index file - to retrieve
the message offset - in order to lookup a message, during
message expiration, or enforcing limits.
The `FileMsgStore` still uses a small message cache which
contains messages that have been just written or looked-up.

Reduce memory usage for FileMsgStore

---

server/log_test.go
server/server.go
server/server_test.go
stores/common.go

Unsubscribe was traced instead of Close and vice-versa.
Also removed the "." from most Errorf/Tracef/Debugf statements.

[FIXED] Debug statement for subscription close and unsubscribe

---

README.md
nats-streaming-server.go
server/conf.go
server/conf_test.go
server/server.go
server/server_test.go
test/configs/test_parse.conf

The server normally creates an ACK subscription per user subscription.
This could lead to a very high number of go-routines if the number
of user subscriptions increases.
The added option limit this number by creating a pool of internal
subscriptions.

[ADDED] Option to configure a pool of ACK subscriptions

---

README.md
nats-streaming-server.go
scripts/cov.sh
server/conf.go
server/conf_test.go
server/server.go
server/server_test.go
stores/filestore.go
stores/filestore_test.go
test/configs/test_parse.conf

Each channel corresponds to a sub-directory and each
sub-directory contain several files. The more channels are
added to the system, the more FDs are needed.
This option is a soft limit instructing the store to
try to keep the number of opened files below this limit.
It is possible that during concurrent read/write across
multiple channels the number of FDs goes above the limit.
Note that this is for the file store's FDs, not the server
as a whole. For instance, if the server embeds the NATS
server, the number of FDs for the nats-streaming-server
process could be much higher (additional FD per Streaming
client connecting to the server). If that's an issue, one
should configure the nats-streaming-server so that it
connects to a remote NATS Server.

[ADDED] FileStore: option to limit use of File Descriptors

---

stores/filestore.go
stores/filestore_test.go

Issue introduced by d9fb4180a20ee8ad93853425f3109ac79867156b.
If a channel is created without message (for instance creating a
subscription on a new channel), the server will panic at the next
background task execution (around 1 second).
Resolves #259

Fixed server panic when channel is created without any message

---

nats-streaming-server.go
server/bench_test.go
server/log_test.go
server/server.go
server/server_test.go
test/test.go

Those APIs used to only return an instance of StanServer. If there
was any issue on startup, the call would panic. The purpose of this
change is to instead return an error. The executable will also
display the error as a fatal error and exit (without the panic).
This would require a change in the Go client tests and for users
running the streaming server programmatically.

[CHANGED] RunServer() and RunServerWithOpts() APIs to return error

---

server/server.go
server/server_test.go
staticcheck.ignore

On server restart, new messages are not sent to consumers until
server attempts to redeliver pending messages.
However, for a simple durable restart, the server was not blocking
new messages until the first attempt to deliver pending messages
was done.
Resolves #261
/cc @ColinSullivan1

[FIXED] Redelivery on durable restart before delivery of new messages

---

util/util.go
util/util_test.go

In situations where an error/trace is printed but there is a
possibility that the print is too frequent, which could cause the
log to quickly fill up, this utility should be used.
You first create a BackoffPrint object giving a minimum and maximum
frequency and a factor at which the frequency is increased.
An Ok() function tells you if it is ok to issue the print statement.
When returning true, the object sets its next print target which
causes subsequent calls to Ok() to return false if they are made
too soon.
The frequency allowed to print is increased by the given factor
anytime the function returns Ok(). It is capped by the max frequency
set when creating the object.
After reaching the max frequency, if a call to Ok() is made after
more than 3x the max frequency since the last call …

Added BackoffTimeCheck utility

---

server/server.go
server/server_test.go
spb/protocol.pb.go
spb/protocol.proto

Until we have clustering, the subject prefix should be unique (but
recoverable from store). The uniqueness per server will be needed
if used in conjunction with channel partitioning.
There was also an issue when a server initially running with -ack_subs
was then restarted without. Currently running subscriptions would
then timeout during ACK because the server was creating individual
subscriptions with the wrong subject.
NOTE: The ack subs pool feature was not yet part of a public release.
If user have started to use it and stop/restart server with this
version, currently running subscriptions would fail to ack messages
since the AckInbox subject exchanged from server to clients will have
changed. Users will need to restart their applications.

Fixed AckSubs pool

---

stores/filestore.go
stores/filestore_test.go

This can happen when the store is being closed. Msgs and Subs stores
are closed first and then the file manager is closed. When stores
are closed, files are removed from the file manager (but manager
status is still opened). So when trying to open a file that is
no longer in the file manager map, return an error instead of panic.

Do not panic when opening a file removed from file manager

---

README.md
nats-streaming-server.go
scripts/cov.sh
server/conf.go
server/conf_test.go
server/ft.go
server/ft_test.go
server/server.go
server/server_test.go
spb/protocol.pb.go
spb/protocol.proto
stores/bench_test.go
stores/common.go
stores/delegate.go
stores/delegate_test.go
stores/filestore.go
stores/filestore_test.go
stores/memstore_test.go
stores/store.go
test/configs/test_parse.conf
util/lockfile_test.go
util/lockfile_unix.go
util/lockfile_win.go
util/util.go
util/util_test.go

This PR is a second take at FT, without the use of RAFT as in #268.
Resolves #263
- Updated the Store Interface to specified recovery and a way for a server to get an exclusive lock on a store. 
- Added file locking based on advisory locks for unix'es and special windows open file call.
- Added a DelegateStore that can be used to create mock stores in order to override some store APIs for test purposes.
- When in FT mode, server starts as a standby until it is elected active, in which case it recovers the state and starts servicing clients.
- Documentation in README.md about FT but also a pass at basic Streaming concepts that were lacking.
/cc @nats-io/core

[ADDED] Shared Storage Fault Tolerance

---

stores/common.go
stores/common_test.go
stores/filestore.go
stores/filestore_test.go
stores/memstore.go
stores/memstore_test.go

The server should not allow to have negative values and therefore
fail to start when any store limit is negative.
Resolves #276

[FIXED] Server starting even with negative store limits

---

README.md
nats-streaming-server.go

It was possible to speficy parameters in the configuration file
as bytes, but not from the command line.
This PR addresses that.
Resolves #275

[ADDED] Ability to specify command line parameters as bytes (e.g 1MB)

---

nats-streaming-server.go
server/conf.go
server/server.go
stores/common.go
stores/limits.go
stores/limits_test.go

The rationale is that when a function returns an error, that function
does not know if the error is going to be printed/logged as standalone
or as a suffix of another error message. So functions should not
return error texts with uppercase.
First letter changed to lower case except for:
- tests (avoid using uppercase in the future, but no need to go
over all tests to change them now)
- panics: since this is the only error that is going to be printed,
starting with uppercase is ok

Changed error texts in fmt.Errorf() calls to not use uppercase

---

server/conf.go
server/conf_test.go
server/server.go
server/server_test.go
stores/limits.go
stores/limits_test.go
util/util.go
util/util_test.go

Since wildcards are not supported - even in the context of
channel limits, the server must reject the configuration of
channel names with wildcards.
Resolves #280

[FIXED] Server not rejecting wildcard channel names in config

---

server/server.go
stores/filestore.go
stores/memstore.go
util/util.go
util/util_test.go

When a channel hits a limit, the store prints a message with
the current/limit values for number of messages and bytes.
This PR prints the size as KB, MB, etc.. instead of raw numbers.
To do so, I have promoted the server's friendlyBytes function
to a util function, and added tests for that.

Updated Store's dropping messages notice to use friendly bytes

---

nats-streaming-server.go

The `--file_slice_max_age` parameter was not being parsed as a duration.

[FIX] Fix parsing of the --file_slice_max_age parameter.

---

.travis.yml
README.md
stores/filestore_test.go

Explicitly specify files and directory to check since we don't want the tool to report failure for `vendor/` or `spb/` (protobuf directory) for which we don't have control.

Added misspell check

---

stores/limits.go
stores/limits_test.go

This was introduced in v0.4.0 when fixing an issue where server
would not report negative values. Basically, prior to v0.4.0, the
limit check preventing a per-channel to be lower than the global
limit was not enforced (but was meant to be).
In v0.4.0 the rule is enforced and with this fix it will be possible
to set a global limit to 0 (unlimited) and lower the limit of a
specific channel.
In future release, we are going to remvoe the check that enforces
a channel limit to be lower than the corresponding global limit.
Resolves #292

[FIXED] Unable to set a per-channel limit if global limit set to 0

---

README.md
server/conf.go
server/conf_test.go
server/server.go
server/server_test.go
stores/limits.go
stores/limits_test.go
stores/store.go

When configuring a channel limits, we can now set its limits to
higher values than the global limits, even set them to unlimited.
Resolves #296

[CHANGED] Channel limit can now be higher than global limit

---

scripts/cov.sh

When adding test for signal handling, this caused the coverage
script to be interrupted and therefore not report code coverage
for server package.
By excluding TestSignal* tests and running then separately
apparently solves the issue.

Fixed coverage script

---

scripts/cov.sh
server/client_test.go
server/server.go
server/signal.go
server/signal_test.go
server/signal_windows.go

PR #305 attempted to fix an issue caused by one of the test
sending a SIGINT to test that server is exiting properly when
receiving that signal. My attempt to exclude those tests and run
them separately using a regex resulted in some tests actually
not running which brought the server.go code coverage down to 90%.
I am removing test that sends SIGINT, which brings the code coverage
for signal.go down to 75%.

Fixed code coverage

---

README.md
nats-streaming-server.go
server/conf.go
server/conf_test.go
stores/filestore.go
stores/filestore_test.go
test/configs/test_parse.conf

By default each channel is recovered sequentially. With SSDs, it
may be faster to do parallel recovery. A FileStoreOptions allows
to specify the number of go routines performing recovery.

[ADDED] FileStore can now recover channels in parallel

---

README.md
server/conf.go
server/conf_test.go
server/partitions.go
server/partitions_test.go
server/server.go
server/server_test.go
spb/protocol.pb.go
spb/protocol.proto
stores/common.go
stores/common_test.go
stores/filestore.go
stores/filestore_test.go
stores/limits.go
stores/limits_test.go
stores/memstore.go
stores/memstore_test.go
test/configs/test_parse.conf
util/sublist.go
util/sublist_test.go
util/util.go
util/util_test.go

This feature allows to have multiple server instances on the
same cluster ID but each instance handling a list of channels.
A given channel must not be defined on more than one instance.
Servers on the same cluster ID try to ensure that this is the case.
This feature also allows to prevent creation of unwanted channels.
A similar feature was proposed by @maxatome in PR #265 that was
not accepted because there were plans for FT and Channels Partitioning.
Resolves #271

[ADDED] Partitioning

---

stores/filestore.go

Compilation in 32-bit architecture fails because of overflow of 0xffffffff.

32-bit issue

---

README.md
nats-streaming-server.go
server/server_test.go

NATS and NATS Streaming options do not overlap, so they can be
combine in the same configuration file. This was already the case
but users would have to pass the unified configuration file with
both `-sc` and `-c` command line parameters.
This PR simply makes the server tries to parse the configuration
file given by `-sc` or `-c` to both NATS and Streaming components.
Resolves #311

[ADDED] Ability to combine NATS and Streaming options in same config

---

stores/filestore.go
stores/memstore.go

Although it does not look like I can reproduce the issue by moving
the clock backward, there was a missing return when the current
time is lower than the first message's timestamp in the message
expiration code (both MemStore and FileStore).
Resolves #318

[FIXED] Missing return in message expiration if clock drifts backward

---

.travis.yml

Doing cross compile for every build takes too long (minimum 35 secs).
Reverting some recent changes and move it back to only when a new
tag is pushed. Dev should ensure cross compile works before getting
ready for a new release.

Cross compile only on new tag [ci skip]

---

stores/common_test.go
stores/filestore.go
stores/filestore_test.go
stores/memstore.go

This would happen if all messages in a channel have expired.
Resolves #344

[FIXED] FileStore's GetSequenceFromTimestamp panic

---

server/server.go
server/server_test.go

Improve the debug statement when creating/destroying a subscription.
Report the sub id and use it in all other subscription related
debug/trace statement to better correlate actions from this
subscription (the inbox was too chatty and difficult to read).

[CHANGED] Debug/trace statements related to Subscriptions

---

stores/filestore.go
stores/filestore_test.go

It was possible that some MsgStore and SubStore were not closed
if the recovery process failed.
This is mainly an issue for tests since in case of the executable,
it did not matter because when the process exits, all files
owned by this process would be closed anyway.

[FIXED] Closing of all channels stores on Recover() error

---

server/monitor.go
server/monitor_test.go

If a durable subscription is online, it appears twice in the list
of subscriptions in the channel endpoint.
Adding IsOffline to indicate when a durable subscription is offline
or not.
Resolves #355

[FIXED] Duplicate subscription in Channel(s) monitoring endpoint

---

nats-streaming-server.go
server/conf.go
server/conf_test.go

The override using natsd.MergeOptions() does not work very well in
that it is not possible to override options if the command line
parameter is actually a default scalar value (false for boolean,
0 for int, etc...). Using the reflection as we did for stan's
options to solve that.
Also, fix #336 introduced a bug that caused some of the NATS command
lines parameters to be ignored (if they were not explicitly covered
in MergeOptions). This issue is not in any public release, but was
in master since #336 was merged.
Again, using overrideWithCmdLineParams() here solve both problems.

[FIXED] Override of NATS related command line parameters

---

server/ft_test.go
server/server.go
server/server_clients_test.go
server/server_delivery_test.go
server/server_durable_test.go
server/server_limits_test.go
server/server_queue_test.go
server/server_redelivery_test.go
server/server_req_test.go
server/server_run_test.go
server/server_storefailures_test.go
server/server_sub_test.go
server/server_test.go
stores/filestore.go
stores/filestore_msg_test.go

- When a subscription is created, it can specify an AckWait() which
is a duration, but the library sends the value as a number of
seconds. For tests, this can lengthen the time the test suite takes.
Making a change that allows to specify a negative value that means
that server interprets as milliseconds. The global boolean is
used to trigger this behavior.
- Changed tests to use smaller AckWait().
- Some FT tests sleep times have been reduced.
- Create explicit NATS connection with nats.ReconnectWait() for
some tests where server is restarted. It shorten the test time
because the client can reconnect faster.
(Note: On Travis, the benefit is not as great as running locally. It looks
like the gain there is about 30%).

Allow AckWait to be specified in ms for tests and some other tweaks

---

server/server.go
server/server_test.go
stores/filestore.go
stores/filestore_sub_test.go

Timer.Reset() should not be called concurrently with a timer
actually expiring. In one of the test, the timer's callback was
invoked directly, with a call to Reset() inside that callback
while the timer may have been firing. This caused the call to
Timer.Stop() to return `true` and yet have the callback firing,
which would cause a panic when calling WaitGroup.Done().
Tweaked a flapping test.

Fixed timers and flapping test

---

server/server.go
spb/protocol.pb.go
spb/protocol.proto

Make it more generic since this may be use more in the future
for any kind of actions that require ordering or gating across
the multiple internal NATS subscriptions.

Refactor CtrlMsg processing

---

server/server.go
spb/protocol.pb.go
spb/protocol.proto

Follow up on previous PR.
This makes the ref counting optional and have an helper function
to create CtrlMsg and corresponding NATS message.
Renamed protobuf field MsgID to RefID.

Update to CtrlMsg processing

---

stores/filestore.go
stores/filestore_msg_test.go

On store close, the files were closed before the expiration routine
was shutdown, which could cause that routine to still try to
open files that have been removed from the internal file manager.
Resolves #365

[FIXED] Possible panic on FileStore.Close() with expiration

---

scripts/cov.sh
stores/common_test.go
stores/filestore_msg_test.go
stores/filestore_sub_test.go
stores/filestore_test.go
stores/memstore_test.go

We use to have some common tests defined in common_test.go that
would be called from memory_test.go and filestore_test.go. In
memory and file store, we would simply create a specific instance
of the store and then call the function corresponding to the
common test.
These tests now become real tests (start with Test instead of test)
and they invoke startTest() that will return a memory or file based
store based on command line parameter (-store). The default is
memory store.

Extract common store tests

---

server/partitions.go
server/partitions_test.go

When a server running in partitioning mode detects that a server
joined the NATS cluster, it checks again that its channels do not
conflict with channels of other servers in this cluster. To
give a chance to the newly joined NATS Server in the cluster to
propagate its subscriptions interest, a delay is added before
sending the list and checking for replies.

[IMPROVED] Partitioning behavior on topology change

---

server/conf.go
server/conf_test.go

We default the logging of time as true, which is a problem when
calling natsd.ProcessConfigFile() since this is returning a new
natsd.Options and so it is impossible to apply the default value
without possible overriding the value that would be set in the
file (that is, if explicitly set to false).
This is hacky: a proper fix would be to add a NATS ProcessConfigFile
version that would accept an Options and fill it out with what is
in the file. This would preserve whatever default we set in the
option given to this new function.

Fixed logging time value when config file is specified

---

server/server.go
server/server_queue_test.go

This happens if a member is stalled and other members are not but
have a number of outstanding acks higher than the stalled member.
Resolves #375

[FIXED] Stalled Queue member may stall the whole Queue

---

stores/common.go
stores/common_sub_test.go
stores/common_test.go
stores/filestore.go
stores/filestore_sub_test.go
stores/memstore.go

The `genericSubStore` was keep track of the subscriptions count
using a simple integer. The problem is that on DeleteSub(), the
count would be decreased, regardless if this subscription either
existed or had been already deleted or never existed.
This was not really a problem since the server should not delete
the same subscription twice.
However, it is safer to make the DeleteSub() store operation
idempotent. To that effect, the count is replaced with a map
in the genericSubStore. The test for max number of subscriptions
now relies on the length of the map. If a subscription is deleted
twice, it will be removed from the map only once and again, the
count is based on size of map, not a separate counter.
Since FileSubStore used a map due to the need during compaction
of the subscriptions …

Fixed SubStore handling of subscriptions count

---

server/server.go
server/server_queue_test.go
server/server_sub_test.go

- When new message arrives in channel and sent to subscription,
a lookup was done even if the subscription was stalled. This
is no longer the case.
- A queue subscription is stalled only when all its members are
stalled. Again, no lookup necessary if the group is stalled.
- Removal of "stalled" debug statement that would be printed
for every message after a subscription has reached its
MaxInflight.

[IMPROVED] Stalled (queue) subscriptions

---

server/server.go
server/server_durable_test.go
spb/protocol.pb.go
spb/protocol.proto

After the server has recovered subscriptions, it detects durables
that are offline (this is a durable subscription for which client
connection was not recovered). However, they were still added
to the list of subscriptions, which means that when a message
was received on a durable's subject, the server will attempt to
deliver it to the durable's old inbox. This would also cause the
message to be added to the pending map, which means that they
would be redelivered every AckWait seconds.
There was also no way to detect a durable subscription that was
closed while the client connection that closed it was actually
recovered by the server.
We ensure now that a durable is added back to the list of active
subscriptions only if it is not offline. It means that we added
a IsClosed to the SubState …

[FIXED] After restart, server sends msgs to offline durables

---

stores/bench_test.go
stores/filestore.go
stores/filestore_test.go

Added locking to this function and removed auto-close on error
condition. Caller is likely to close the store if recovery fails.

[CHANGED] FileStore.Recover() closing store on error.

---

server/monitor.go
server/monitor_test.go

When all members of a durable queue subscription were offline,
the monitoring page would not show the durable queue subscription
anymore.
Resolves #385

[FIXED] Monitoring of offline durable queue subscription

---

nats-streaming-server.go
server/conf.go
server/conf_test.go
test/configs/test_parse.conf

After upgrading vendor directory for gnatsd, we can now use
natsd.ConfigureOptions() from PR https://github.com/nats-io/gnatsd/pull/578
We follow this model for NATS Streaming and chain the two
configuration of options.
This will solve any issue that we had with options override.

[FIXED] Override of options from configuration files

---

stores/common_test.go
stores/filestore.go
stores/filestore_test.go

After a channel is recovered, its related files are closed. They
will be re-opened on demand when needed.
This allows to recover possibly lots of channels even without
the file descriptor limits set on recovery.

[IMPROVED] FileStore closes files on recovery

---

server/server.go
server/server_queue_test.go
server/server_redelivery_test.go

This was introduced by #378. The queue group as a whole may not
be stalled (that is, not all members are stalled), but if a server
processes the ack of one of the member that causes that member
to unstall, then it needs to attempt to send available messages.
It was not doing that.
Related to #378

Fixed stalled queue

---

server/server_redelivery_test.go
server/server_test.go

These tests were flapping in clustering branch. Adding some timeout
for the check instead of fixed sleep before check. Increase the wait
before restarting server when checking redeliveries on startup.

Fixed flapping tests

---

server/conf.go
server/conf_test.go
server/partitions_test.go
server/server.go
stores/limits.go
stores/limits_test.go
util/util.go
util/util_test.go

This was a problem with FileStore implementation since channels
are not meant to translate into sub directories (but be flat).
The server now rejects channels containing `/`, regardless of
the store type being used.
Resolves #403

[FIXED] Server is not rejecting `/` in channel names

---

nats-streaming-server.go
server/clustering.go
server/clustering_test.go
server/conf.go
server/server.go
vendor/github.com/hashicorp/raft-boltdb/bolt_store.go
vendor/manifest

Apply the fsync configuration from the file store to the Raft log
backend. This allows disabling disk syncing on every write to the
Raft log which improves performance. While this creates some risk,
the thought is if we are replicating to enough nodes, the replication
itself is sufficient for HA of data since the likelihood of more than a
quorum of nodes failing is low.
Note: we may want to consider disabling fsync as the default in
clustered mode for performance reasons, similar to what Kafka
does.
@kozlovic

Allow configuring fsync for Raft log

---

.travis.yml
Dockerfile
scripts/cross_compile.sh

- Added the ARM64v8 to the list of executables to be generated on
release
- Updated Dockerfile to generate executables that will be used
in nats-streaming-docker to provide multi-platform support
Resolves #412

[ADDED] ARM64 to list of builds and updated Docker file

---

server/clustering_test.go
server/server.go

Default Raft log to be stored at `./<cluster-id>/<node-id>`.

Fix clustering defaults settings

---

nats-streaming-server.go
server/clustering.go
server/clustering_test.go
server/conf.go

Now clusters can be bootstrapped either by starting a node in bootstrap
mode and allowing other nodes to automatically join or by starting
servers with a cluster configuration. Once the cluster is formed, new
nodes can join the cluster automatically.
@kozlovic

Support manual bootstrap configuration of cluster

---

server/clustering.go
server/server.go

Instead of applying bootstrap settings to channel Raft nodes, pull the
cluster configuration from the metadata Raft group. This allows for
better balancing of leaders.
Also fix a bug where the default Raft log path was not correctly set
when recovering channels.
@kozlovic

Better balancing of Raft leaders

---

server/clustering_test.go
server/server.go
server/server_test.go

Fixes a race condition in `processClientPublish` and adds some tracing to `publishWithRetry` test function for debugging purposes.
@kozlovic

Clustering race condition fix

---

server/ft.go
server/ft_test.go

An FT Standby server that tried to get the exclusive lock when
missing FT heartbeats would exit if it got an error (as opposed
to knowing that it did not get the lock). In otherwords, the error
was considered fatal.
But with the introduction of SQL store, losing the DB connection
would result in standby exiting. So the server will now report
the error but go back to the loop of trying again after the
missed HB interval.
Resolves #446

[CHANGED] FT Standby exit on error trying to get exclusive lock

---

server/client.go
server/partitions_test.go
server/server.go

In partitioning mode, when a client connects, the connect request
may reach several servers, but the first response the client gets
allows it to proceed with either publish or subscribe.
So it is possible for a server running in partitioning mode to
receives a connection request followed by a message or subscription.
Although the conn request would be first in the tcp connection, it
is then possible that the PubMsg or SubscriptionRequest be processed
first due to the use of different nats subscriptions.
To prevent that, when checking if a client exists, in this particular
mode we will possibly wait to be notified when the client has been
registered.

[FIXED] Possible race between connect and pub/sub with partitioning

---

stores/filestore.go
stores/filestore_msg_test.go
stores/filestore_sub_test.go
stores/filestore_test.go

There have been 2 reports that server fails to start due to a
subscription record of type 0, which is not possible. Without
access to store files, the suspicion is that the file has for some
reason zeros at the end of the file. If there are enough zeros to
fill the record header (8 bytes), then the function readRecord()
would return no error but a record type of 0, which would cause
calling code to return an error.
Files that are recovered have now the following logic:
- If the expected record header (or message index record) is fully
read but all zero, the file is rewinded to prior this record and
truncated and no error is reported.
- If there is less bytes that needed, the "unexpected EOF" is now
augmented with information about how many bytes were expected
and how many were actually …

[IMPROVED] Handle end of files filled with null bytes

---

server/clustering_test.go
server/server.go

Use the fix @kozlovic made to address the client connect race condition
in clustering. This means we also no longer need `publishWithRetry` in
the clustering tests.

Fix clustering client connect race

---

stores/sqlstore.go
stores/sqlstore_test.go

If all messages expire and then the server is restarted, the
first sequence would be 1 less than it should be.

[FIXED] SQLStore Message first sequence after all messages have expired

---

server/partitions.go
server/partitions_test.go
server/server.go

In Partitioning mode, when a server starts, it tries to see if
another server in the NATS cluster has incorrectly configured the
same channel(s). However, an FT server should do this test only
when it activates.
Resolves #453

[FIXED] FT Standby may fail to start in Channels Partitioning mode

---

stores/common_test.go
stores/filestore.go

It would panic if we did not call FileStore.Recover() first. The
Server is always calling Recover() first, so this is not an issue
for Streaming server, but still fixing the FileStore implementation.

[FIXED] FileStore.Init() implementation

---

server/server.go
server/server_run_test.go

In issue #215, we incorrectly kept the record of a queue durable
member that closed. After the fix, on recovery this record would
not be recovered and a warning was printed. However, the record
was not deleted and subsequent restarts would continue to print
the warning.
This PR will print the warning as usual but then delete the record,
which means that at the next restart, the record (and therefore
warning) should no longer be recovered.

[FIXED] Remove ghost queue durable when such record is recovered

---

server/server.go
server/server_limits_test.go
server/server_run_test.go

On startup the server displays global and per-channel limits.
If a channel override a limit to set it to unlimited, they would
incorrectly be displayed as -1.

[FIXED] Display of per-channel limits when set to unlimited

---

server/server.go
server/server_limits_test.go

When the MaxSubscriptions limit is set, an application would correctly
get an error when trying to create a subscription more than the limit.
However, this subscription would still appear in the list of
subscriptions for that client (as seen in the monitor endpoints).
Resolves #467

[FIXED] Failed subscription appears in client's list of subscriptions

---

README.md
server/monitor.go
server/monitor_test.go
server/server.go

For offline durable (queue) subscriptions, the client_id was empty,
which would prevent one to delete a durable subscription without
knowing the clientID.
Resolves #472

[IMPROVED] Display client_id in monitor endpoints for offline durables

---

server/clustering.go
server/clustering_test.go
server/server.go

Auto-configuration subjects were not using the cluster ID which
would cause nodes to possibly join the wrong cluster.
Resolves #481

[FIXED] Inability to run several clusters on same NATS network

---

README.md
server/clustering.go
server/clustering_test.go
server/server_run_test.go

The servers started with `-cluster_bootstrap` will emit a message
every second that each server started with this parameter listen
to. When they detect other servers with this flag, they will
report the misconfiguration and exit.
Resolves #476

[FIXED] Clarify usage of bootstrap in README and add defensive code

---

nats-streaming-server.go
server/server_test.go
stores/sqlstore.go
stores/sqlstore_test.go

These were moved to nats-streaming-server.go (main) and to tests
files where needed. That will allow users that import NATS Streaming
server code and SQL drivers to work properly.
Resolves #485

[FIXED] Removed imports of SQL drivers from Store.go

---

server/clustering.go
server/clustering_test.go
server/server.go
server/snapshot.go

This could happen when applying raft log entries to the state machine
when s.raft was not yet created. The fix could have been to move
s.raf.leader to the server structure. Instead, I have refactored
the creation of the raft node a bit so we can use the leader and
initialized atomic from s.raft instead of StanServer.
Also made s.raft.shutdown() idempotent.

[FIXED] Clustering: possible panic on startup

---

logger/logger_test.go
server/clustering_test.go
server/server_test.go
util/util_test.go

For instance:
```
go test -v -run=TestClustering ./server -persistent_store=sql
```

Updated testsuite so one can run clustering tests with SQL store

---

server/server.go
server/server_run_test.go

This is required for users wanting to embed NATS Streaming.
Resolves #499

[ADDED] GetNATSOptions() to return an empty NATS Options structure

---

server/clustering_test.go
server/server.go

Memory store is not supported in clustering mode. Fail to start
if users attempt to do so.

[FIXED] Clustering: Reject use of memory store

---

server/server_limits_test.go
server/server_test.go
stores/filestore.go
stores/filestore_msg_test.go
stores/filestore_test.go

The server test package and stores test package may have tried
to set/reset a file store variable at the same time.

Fix possible race in tests setup

---

server/clustering_test.go
server/conf_test.go
server/server.go
server/server_test.go

This is an addition to PR #522.

Remove NodeID from Peers in RunServerWithOpts()

---

server/server_test.go
stores/sqlstore.go
stores/sqlstore_test.go

This is due to the use of a now reserved word. Need to be escaped
with the "`" character. This character is used only for mysql
driver, not postgres (otherwise, it would break).
Resolves #536

[FIXED] SQLStore: Unable to run against MySQL 8.0.2+

---

server/server.go
server/server_sub_test.go
server/server_test.go
server/snapshot.go

This issue exists only if an application is left running while
server prior to 0.8.0 is stopped and replaced with a version
0.8.0+ (up to current version of 0.9.1).
Resolves #539

[FIXED] Acks processing when moving from 0.7.2 to 0.8.0+ if subs still running

---

.travis.yml
logger/logger_test.go
util/util_test.go

Support for flag -sql was added to each package, but when adding
the TestMain on logger and util, call to os.Exit(m.Run()) was missing.
This resulted in those tests to not run and affected code coverage.

Fixed TestMain for logger and util

---

server/raft_transport.go

When the NATS transport is down, the leader from a Raft cluster will try to 'Dial' again to the other nodes that it has perceived by making a unique subscription to a subject like:
```
raft.test-cluster.$NODE_NAME.$CLUSTER.request._INBOX.$NUID
raft.test-cluster.4tSGOGQFyl6FOd8felGDeR.test-cluster.request._INBOX.4tSGOGQFyl6FOd8felGDsZ
```
then sending a request expecting single response, but since the transport is down these subscriptions become accumulated by the client.
In order to prevent this, a potential fix could be to try skipping Dial again in case the client is aware that it is not currently connected to NATS.
Fixes #550 
Signed-off-by: Waldemar Quevedo <wally@synadia.com>

[FIXED] Clustering: avoid accumulation of internal RAFT subscriptions when disconnected

---

server/server.go
server/server_redelivery_test.go

If the streaming server is connecting to a standalone NATS Server,
and the streaming server is redelivering messages, if a disconnect
occurs, these redeliveries may be buffered by the NATS client
library used by the Streaming server. When the NATS Server is restarted
and the Streaming server reconnects, the pending buffer is flushed,
which if the client has reconnected before the server, would cause
the client to receive possibly a serie of the same redelivered
messages, even if the client is ack'ing them.
To prevent this, set the reconnect buffer to -1 to prevent any
buffering.

[FIXED] Avoid possible duplicate redeliveries after message is ack'ed

---

README.md
nats-streaming-server.go
server/conf.go
server/server.go
server/server_delivery_test.go
server/server_storefailures_test.go
stores/common_msg_test.go
stores/filestore.go
stores/filestore_msg_test.go
stores/filestore_test.go
stores/memstore.go

Works for errors due to unexpected EOF errors, when the files have
not been fully flushed, etc..
See README.md for details.
Resolves #557

[ADDED] FileStore: option to truncate corrupted store files

---

server/conf.go

This was observed in the context of Docker.

[FIXED] Possible issue with confi files using include directive

---

stores/sqlstore.go
stores/sqlstore_test.go

This is related to #569.
It looks like the SQL statement for postgres driver against a
cockroach db would not work. It works fine with Postgres database.
I had another look at that specific statement and rewrote it for
both MySQL and Postgres. This statement works now against a
cockroach db.. However, there would still be an issue in using
cockroach db it seems due to the "SELECT FOR UPDATE" for locking
that seem is not supported there.
Still, there may be value in updating this statement.

Update an SQL statement for Postgres

---

server/clustering_test.go
server/server.go
server/server_durable_test.go
server/snapshot.go
stores/bench_test.go

Especially with n to m. Use a dedicated connection for receiving
acks and use ack subscription's per sub instead of one per channel.

[IMPROVED] Subscriptions performance

---

server/server.go

Moved some global variables inside the StanServer object to avoid
races if program starts more than 1 server at a time. This happens
in that test, but technically, it could happen if users run
NATS Streaming servers from their application and start more than
one instance at a time..

Fxed RACE for TestPartitionsClientPings test

---

server/clustering.go
server/clustering_test.go
server/server.go

If a durable subscription (can apply to durable queues too) is
created with a start position other than SequenceStart, and this
subscription receive some messages, then is closed. At that time
either more messages are sent or there were already more messages
in the channel, then after a cluster restart (all nodes are
restarted), then when the durable (queue) is resumed, it would
seem to not receive any messages in the channel. Only new messages
produced after the cluster is restarted would be delivered.

[FIXED] Durable subscriptions miss messages after cluster restart

---

.travis.yml
server/client.go
server/server.go
server/server_clients_test.go

This is for newer clients sending PINGs to the server. If a server
is restarted, the information allowing the server to detect if
the client is still valid was not properly recovered, causing the
server to return an error back to the client which then caused it
to disconnect.
This does not affect older clients or when servers were running
in clustering mode.
Resolves #592

[FIXED] After server restart client sending PINGs are disconnected

---

.travis.yml
server/server.go
server/server_redelivery_test.go

If a subscription has pending messages (unack'ed) during server
recovery, then the server would mark it as stalled because it
was checking the number of pending messages vs the MaxInflight
value before that value was set from the recovered subscription
record.
Resolves #594

[FIXED] Subscription incorrectly marked as stalled after restart

---

server/server.go
server/server_clients_test.go

If a client has durable subscriptions and some unacknowledged
messages, then crashes, the server will detect the HB failure and
skip the redelivery until the connection is closed.
If the client is restarted and durables resumed, then the
server should redeliver messages. Since v0.10.0, it is possible
that this client's subscription are already marked has having
a failed HB which would prevent redelivery.
Resovles #600

[FIXED] Skipped redelivery not resolved after client restart

---

server/clustering_test.go
server/server.go
server/server_queue_test.go
server/server_storefailures_test.go
server/server_test.go

If a durable queue had no member running but had unacknowledged
messages, and if the server (or cluster in clustered mode) was
restarted, redelivery of unacknowleded messages may occur when
the queue was restarted but new messages would not be delivered.
Resolves #584

[FIXED] Possible stall of durable queue after server/cluster restart

---

server/server.go
stores/filestore.go
stores/filestore_msg_test.go

Index files are normally not created empty, but if the server were
to stop/crash after the file is created but before the first record
is appended, then on recovery the server would panic (true only for
servers 0.10.0+).
Resolves #608

[FIXED] FileStore: Possible panic on recovery with empty index file

---

stores/sqlstore.go
stores/sqlstore_test.go

This could happen if the server was previously started with caching
enabled (the default) and restarted with caching disabled.
The panic would occur if the store recovered subscriptions pending
messages/acks.
Resolves #618

[FIXED] SQL: Possible panic on recovery with -sql_no_caching

---

logger/logger.go
logger/logger_test.go
server/server.go
server/signal.go
server/signal_test.go

- On file log re-open, we were incorrectly call s.natsserver.ReOpenLogFile()
since when using remote NATS Server, s.natsserver would be nil.
- Even when embedding, re-open caused a new logger to be set in the
nats server's logging object, not the stan server.
Reproduce the logic of the NATS Server's re-opening of the log file
in Streaming Server's own logger.
Resolves #621
Resolves #622

[FIXED] Possible panic and other issue with file logger

---

.travis.yml
server/signal.go
server/signal_test.go

The server was trapping only SIGINT to do a proper shutdown.
In Docker, however, the `docker stop` command sends SIGTERM. So
if we want the server to do proper shutdown, we need to trap
SIGTERM.
Resolves #624

[ADDED] Trap for SIGTERM

---

stores/sqlstore.go
stores/sqlstore_test.go

In some conditions, the subscription's last sent message sequence
was not properly persisted, which could result in redeliveries on
server restart.
This would not happen with `-sql_no_caching` configuration.
Resolves #626
Resolves #619

[FIXED] SQLStore: Previously ack'ed messages may be redelivered

---

README.md

Added some clarification about NATS Streaming Clustering configuration
when using an existing NATS cluster.
This is in reference to https://github.com/nats-io/go-nats-streaming/issues/192

[UPDATED] Clustering example in README [ci skip]

---

logger/logger.go
logger/logger_test.go
server/clustering_test.go
stores/raftstore_test.go

If the logger is file based, allow file to be closed for proper
cleanup. This was found when running tests on Windows where test
log could not be cleaned-up because the file was still opened.
Also added some missing defers that would also cause some files
to fail to be deleted on test exit.

Added Close() for StanLogger to allow resources to be released

---

README.md

To be merged only when nats-io/nats-site#376
is merged and site is live.

Change README nats.io URL documentation back [ci skip]

---

server/clustering_test.go
server/server.go

If the leadership is lost while a node was just previously
elected leader, the election will fail but could result in panic.
Resolves #662

[FIXED] Clustering: Possible panic leader election

---

server/monitor.go
server/monitor_test.go

We are monitoring nats-streamin-service with prometheus-nats-exporter, and since nats-streaming-service doesn't have the open files count as a metric, the exporter can't export it. 
We had an issue yesterday due to "too many open files", so, this PR adds the `max_fds` and  `open_fds` metrics on OSs that have a `/proc`.
I used prometheus/procfs for that, since it is already vendored and also supports all I needed.
Hope this is something you want to add :) 
Cheers
cc/ @aricart

[ADDED] serverz expose open files and max open files

---

server/server.go
server/server_limits_test.go
server/server_test.go

Trigger the channel delete timer (when max inactivity is set)
when a connection is closed (either explicitly or due to lack
of HB).
Resolves #690

[FIXED] Channel not deleted if sub not explicitly closed

---

server/server.go

Async errors can have a nil sub parameter, e.g. with publish permission violations.  This fixes a panic that occurs in that case.
Signed-off-by: Colin Sullivan <colin@synadia.com>

[FIXED] Panic in async error handler when sub is nil

---

stores/common_msg_test.go
stores/filestore.go
stores/memstore.go

In GetSequenceFromTimestamp, if the timestamp only match the last
message, it could ignore the last one and return ms.last + 1.
Resolve #686

[FIXED] timestamp compare issue in GetSequenceFromTimestamp

---

stores/filestore.go
stores/filestore_msg_test.go
stores/memstore.go

Following PR #687, changed the way FileStore searches for the
first sequence greater or equal to given timestamp.

Revisit FileStore GetSequenceFromTimestamp()

---

server/client.go
server/partitions_test.go
server/server.go

When a published message is processed by the server and the
associated clientID is not found, in partitions mode, we need
to wait to see if the processing of the connect is going to
happen soon. Delay here is delaying all other inbound messages.
We don't have a choice here, but reducing the wait time and
also remembering the failed clientIDs so that next invalid
message is processed fast (map lookup).
Also removed this check from clustered mode. It used to be required
when clustering was using a RAFT group per channel and one for
meta data, but this is no longer the case (single RAFT group).

[FIXED] Delayed msg processing when getting invalid pub requests

---

server/monitor.go
vendor/github.com/prometheus/procfs/bcache/get.go
vendor/github.com/prometheus/procfs/buddyinfo.go
vendor/github.com/prometheus/procfs/fs.go
vendor/github.com/prometheus/procfs/internal/util/parse.go
vendor/github.com/prometheus/procfs/internal/util/sysreadfile_linux.go
vendor/github.com/prometheus/procfs/ipvs.go
vendor/github.com/prometheus/procfs/mdstat.go
vendor/github.com/prometheus/procfs/mountstats.go
vendor/github.com/prometheus/procfs/net_dev.go
vendor/github.com/prometheus/procfs/nfs/nfs.go
vendor/github.com/prometheus/procfs/nfs/parse.go
vendor/github.com/prometheus/procfs/nfs/parse_nfs.go
vendor/github.com/prometheus/procfs/nfs/parse_nfsd.go
vendor/github.com/prometheus/procfs/proc.go
vendor/github.com/prometheus/procfs/proc_io.go
vendor/github.com/prometheus/procfs/proc_limits.go
vendor/github.com/prometheus/procfs/proc_ns.go
vendor/github.com/prometheus/procfs/proc_stat.go
vendor/github.com/prometheus/procfs/stat.go
vendor/github.com/prometheus/procfs/sysfs/class_thermal.go
vendor/github.com/prometheus/procfs/sysfs/net_class.go
vendor/github.com/prometheus/procfs/sysfs/system_cpu.go
vendor/github.com/prometheus/procfs/xfrm.go
vendor/github.com/prometheus/procfs/xfs/parse.go
vendor/manifest

With this update, OpenFiles is now an int64, so casting to int()
since our Serverz.MaxFDs has been defined as int.
Resolves #737 (not the go.mod part, but OpenFiles issue)

[UPDATED] Prometheus/procfs vendor

---

server/clustering_test.go
server/server.go

An internal subscription was not unsubscribed when the channel
was deleted.

[FIXED] Clustering: leak of go routine on channel delete

---

server/clustering.go
server/clustering_test.go
server/server.go

If a server was leader and lost leadership while about to delete
a channel due to inactivity, but then becomes a follower and need
to replicate data for this channel, there was a risk that the
server would panic trying to store messages for this channel.
Resolves #757

[FIXED] Clustering: possible panic in follower due to maxInactivity

---

server/clustering_test.go
server/server.go

In some cases, it was possible for a follower to become leader
but be unable to complete all the actions to fully become leader.
The underlying issue was that if there were snapshots to send
to the followers, those were unable to restore the snapshot
because the new leader was not listening to those requests yet.
Also, there could be a risk that a channel is part of the
snapshot sent to followers but then would be deleted while
the followers would try to install the snapshot.
Resolves #762

[FIXED] Clustering: unable to complete leadership actions

---

README.md

NATS Streaming server uses some default values, but if user
experience some RAFT issues, he/she can try to tweak those.
Resolves #760
[ci skip]

[FIXED] Missing raft timeout configuration

---

server/raft_log.go

An user reported the panic due to a volume full issue and was
asking if we could print a more explicit error message (#754)
It seems that there is an issue with Boltdb and a recent param
called NoFreelistSync. When set to true and a transaction is
rolled-back, a panic occurs.
This boolean was used when moving from boltdb to etcd/bbolt
in the recent 0.12.0 release.
Disabling for now until the underlying issue can be resolved.

[FIXED] Panic on raft write issue

---

stores/store.go

Fixes `MaxInactivity` being exposed in camel case when polling from monitoring endpoint to be consistent with other fields:
Before:
```sh
curl http://127.0.0.1:8222/streaming/storez
... 
"limits": {
"max_channels": 100,
"max_msgs": 1000000,
"max_bytes": 1024000000,
"max_age": 0,
"max_subscriptions": 1000,
"MaxInactivity": 0
},
```
After:
```sh
curl http://127.0.0.1:8222/streaming/storez
... 
"limits": {
"max_channels": 100,
"max_msgs": 1000000,
"max_bytes": 1024000000,
"max_age": 0,
"max_subscriptions": 1000,
"max_inactivity": 0
},
```
Signed-off-by: Waldemar Quevedo <wally@synadia.com>

Add json field to MaxInactivity using snake case

---

server/server.go

Allows custom NATS client options to be set on the internal NATS client connection.
I am integrating NATS streaming into Chef's Automate product. Automate internally has a Microservices architecture with connections between services secured by mutual TLS cert verification. Automate is usually deployed by our customers on their own infrastructure so we have elected not to rely on using hostnames in our certificates' CN fields; instead we use the internal service names (i.e., something like `event-service` instead of `host.example.com`). In go it's fairly straightforward to adapt to this by setting the `ServerName` field of the `tls.Config` struct when it's exposed, as the NATS go client does; however NATS streaming does not currently expose the full set of NATS client options.
Yep! Happy …

Allow custom nats client options server configuration

---

.travis.yml

Go 1.10 is out of support and incompatible with staticcheck

Removing Go 1.10 from Travis matrix builds

---

stores/filestore.go
stores/filestore_msg_test.go
stores/sqlstore_test.go

When removing the first message in a log, there is a possibility
that an I/O error occurs, which then translated to an object
being nil and being dereferenced, which would cause a panic.
Resolves #778

[FIXED] FileStore: possible panic when removing old messages

---

server/clustering_test.go
server/server.go

In some situations, it could be possible for a node becoming leader
to not properly register (actually unregister) the client's timer
supposed to check for client health (response to server HBs). This
could lead to clients and their subs not being removed from the
server.
Fixes #791

[FIXED] Clustering: clients possibly not removed due to removed HB timer

---

README.md
server/monitor.go
server/monitor_test.go

A new field indicates the RAFT role of the node when running in
clustered mode. The possible values are `Leader`, `Follower` or
`Candidate`.
Resolves #792

[ADDED] Cluster role in serverz endpoint

---

server/clustering_test.go
server/server.go
stores/common_sub_test.go
stores/common_test.go
stores/raftstore.go
stores/raftstore_test.go

This was introduced by #802. The server was replacing the sub's ID
after the call to CreateSub(), but that meant that DeleteSub() in
the underlying sub store would not find that subscription, which
will then cause it to report too many subscriptions after a while
because the removed subscriptions were not removed from their
internal map.
The approach in this PR is to make RaftSubStore completely bypass
the underlying SubStore. It should work with a mix of servers
of different versions.
Resolves #809

[FIXED] Clustering: erroneous "too many subscriptions per channel"

---

server/clustering.go
server/clustering_test.go
server/snapshot.go

[FIXED] Clustering: possibly getting empty messages

---

server/monitor_test.go
server/server.go

The number of subscriptions was incorrectly increasing when a durable
subscription was resumed.
The proper behavior is as follows:
- a durable is started for the first time, count increases
- this durable is closed (but not unsubscribed), count unchanged
- durable is unsubscribed, count decreases
- a durable queue group is created, count increases
- a member added, count increases
- a member leaves, count decreases
- the last member leaves (but group remains because durable), count
is unchanged.
- group is unsubscribed, count decreases.
for non durable subscriptions (queue or not), when a subscription
is created, count increases, when closed or unsubscribed, count
decreases.
Resolves #819

[FIXED] Number of subscriptions in /serverz endpoint is incorrect

---

server/server.go
server/server_storefailures_test.go
server/server_sub_test.go

Account for offline durables and for possible error on sub create

---

server/clustering_test.go
server/monitor.go
server/server.go
server/server_sub_test.go

Replaces the use of a variable that was supposed to be updated
on subscription create/remove. It was started to be a bit brittle.
Provide a function that computes the number of subscriptions
(including offline durables/queue durables).
This is a bit more costly than using the variable but will be
less prone to issues.
Resolves #819

[FIXED] Incorrect number of subscriptions in /streaming/serverz

---

server/server_delivery_test.go
stores/sqlstore.go
stores/sqlstore_test.go

Issue was due to the fact that we were not keeping track of the
maximum row number, so if a subscription that are pending state
saved in row 1 and 3 and the last recovered subscription had
state in row 2, and then the next update was for the first subscription
the SQL statement would have tried to add a row with ID 3 which
already existed.
Resolves #741

[FIXED] SQLStore: panic when updating subscriptions pending state

---

server/clustering_test.go
server/server.go
server/snapshot.go

When a snapshot is performed prior to messages being removed (either
expired or remove due to count/size limits), a node that would
restore from this snapshot would ask the leader to send messages
which indexes (first/last) are in the snapshot.
Both leader and node would stop the restore when the first unavail
message was found.
Resolves #834

[FIXED] Clustering: restore snapshot with some messages no longer avail

---

server/clustering.go
server/raft_transport.go
server/raft_transport_test.go

This speeds up clustering tests from 175s down to 98s.

Changes to how raft node is shutdown

---

server/clustering.go
server/clustering_test.go
server/monitor.go
server/server.go
server/snapshot.go

This could happen if the leader took a snapshot while messages were
not yet expired, then a node is started without state and tries
to restore from this snapshot. If the messages have expired by then,
no message would be stored. If that node later did a snapshot itself,
it would persist in it the first/last being zero. If no message are
published and this node becomes leader, it would start storing
messages at the wrong sequence and would also send the bad snapshot
to other nodes.
Resolves #833

[FIXED] Clustering: channel first/last sequence may fall to zero

---

.travis.yml
Dockerfile
README.md
server/server.go

Release 0.14.2

---

server/clustering.go
server/clustering_test.go
server/server_delivery_test.go
server/server_test.go
stores/sqlstore.go
stores/sqlstore_test.go

With the SQLStore, this would cause messages to be accumulated
in write cache causing memory growth and no message stored in the
DB until the follower shutsdown or become leader.
Resolves #846
Also made server tests skip SQL specific tests if running tests
with `-sql=false` for users that don't have/want to setup an
SQL server.
Resolves #845

[FIXED] Clustering: message store not flushed on followers

---

server/server.go
server/server_queue_test.go

In some situations, it could be possible for a queue member to
appear stalled eventhough there are still messages to be delivered
and the member is not actually stalled (number of pending lower than
maxInflight). Sending new messages or starting a new member would
unstall it.
Resolves #862

[FIXED] Possible stall of queue member

---

server/clustering_test.go
server/server.go
server/server_redelivery_test.go

When a queue member has unacknowledged messages and is leaving the
group, these messages are supposed to be immediately redelivered
to existing queue members. However, if a target member had unack'ed
messages of a sequence lower than the reassigned messages these
reassigned messages would not be redelivered until after the AckWait.
The issue was introduced in PR https://github.com/nats-io/nats-streaming-server/pull/729
with the incorrect change in ordering algo for the messages that
should expire.
Resolves #869

[FIXED] Redelivery of unack'ed msgs of leaving queue member

---

nats-streaming-server.go
server/conf.go
server/conf_test.go
stores/common_test.go
stores/filestore.go
stores/filestore_msg_test.go
stores/filestore_test.go
test/configs/test_parse.conf

A new option `file_read_buffer_size` is added and defaults to 2MB.
If not set to 0, when a message is read from disk, the store will
actually read the following messages, up to that buffer size, and
add them to the internal cache (which already existed and has a
default TTL of 1sec).
This will speed up lookups of following messages since they are
likely to be in the cache.

[ADDED] FileStore: read ahead capability

---

README.md
nats-streaming-server.go
server/conf.go
server/conf_test.go
stores/filestore.go
stores/filestore_test.go
test/configs/test_parse.conf

Added ability to have the store auto flush/sync stores at regular
interval. This can be useful if one wants to disable sync at every
Flush() but still wants to have files being sync'ed from time to
time.

[ADDED] FileStore: auto sync interval

---

server/clustering_test.go
server/server.go
stores/filestore.go

- SubStore was still being sync'ed even when there was no activity
(on store close)
- Add needSync check for MsgStore too
- Add unsub request in a test in case subscriptions were made before
their channel was deleted

FileStore auto-sync updates

---

stores/common.go
stores/common_msg_test.go
stores/memstore.go
stores/sqlstore.go
stores/sqlstore_test.go

This comes into play with clustering when messages are replayed
and their timestamp may now be well in the past.
Resolves #915

[FIXED] Expire messages based on their timestamp

---

server/clustering_test.go
server/server.go
server/server_delivery_test.go

There is a possible race between trying to send new messages and
the storing of new messages that could cause the server to skip
some messages.

[FIXED] New messages skipped on processing ack

---

server/clustering_test.go
server/server.go

This happens when a queue subscriber with pending message is
being removed and messages are reassigned to other members. Each
node was doing this operation resulting possibly in messages
being "assigned" to different qsubs.
After a new leader election, it would be possible for messages
to be redelivered, due to this.
Resolves #934

[FIXED] Clustering: possible wrong pending_count on followers

---

.travis.yml
server/server_run_test.go
server/server_test.go
stores/filestore.go
stores/filestore_msg_test.go

Differentiate error reading from the index file as opposed to
not find a given sequence. Gaps should not exist but if that happens
it would prevent messages from being expired or next messages to
be delivered.
Resolves #928

[FIXED] FileStore: handle possible sequence gap in index files

---

server/server.go
server/server_queue_test.go
server/server_storefailures_test.go
server/snapshot.go

A race between a durable queue subscriber close and create could
cause the server to store multiple shadow subscriptions.
Resolves #950

[FIXED] Duplicate shadow durable queue sub due to race

---

server/server.go
stores/pqdeadlines/pqdeadlines.go
stores/sqlstore.go

I refactored several if-else statement to more readable switch statements.
Furthermore I refactored a single which statement to a if statement.

Ifelseswitch

---

server/monitor.go
server/monitor_test.go
server/server.go

Unlike total_msgs/bytes that represent the total number of messages
stored, in_msgs/bytes and out_msgs/bytes are the messages received
by the server and sent to clients.
The `in_msgs` counter is updated when processing inbound client
messages.
The `out_msgs` counter is updated when sending a message to a subscription,
either as a new or redelivered message.
Note that the size for in_bytes/out_bytes is different because these
values represent the bytes received (a PubMsg protobuf) and sent
(a MsgProto protobuf) that have different overhead.
Resolves #974

[ADDED] In/Out Msgs/Bytes in /serverz monitoring endpoint

---

server/clustering_test.go
server/monitor_test.go
server/server.go
server/server_clients_test.go
server/server_run_test.go
server/signal_test.go

This helps speed-up tests on my Windows VM.

Changed default options host to loopback instead of localhost

---

server/raft_log.go

This option had been disabled due to a defect in bbolt implementation.
Since it has been fixed, re-enable it.
Was commented out in https://github.com/nats-io/nats-streaming-server/pull/766

[IMPROVED] Use NoFreelistSync for RAFT's bbolt store

---

server/clustering.go
server/raft_transport.go
server/timeout_reader.go

Keep a 2sec for the dial and flush, but increase the timeout for
read operations. This will reduce the risk of getting these
type of errors:
```
[ERR] STREAM: raft-net: Failed to flush response: write to closed conn
```

[FIXED] RAFT Transport timeouts

---

server/clustering.go

- Some of raft headers were truncated (ft-net instead of raft-net)
- RAFT debug level were traced as streaming trace level.
Resolves #986

[FIXED] Incorrect RAFT logging.

---

stores/sqlstore_test.go

In https://github.com/nats-io/nats-streaming-server/pull/538 we
escaped `row` in the SQL code, but then this test does not have
it escaped. I recently updated my local MySQL server and got the
test failure.

Fixed SQL test

---

server/signal_test.go

This test requires the nats-streaming-server to be installed first.
Added that to the error message.
Resolves #1002

Fixed test comment and error message

---

.travis.yml
server/clustering_test.go
server/monitor_test.go
server/server.go
server/server_queue_test.go
server/server_redelivery_test.go
server/server_run_test.go
server/server_storefailures_test.go
server/server_test.go
server/signal.go

This is for users embedding the NATS Streaming Server or for tests
where a server is shutdown but process continues running for a while.
Cleaned-up some tests.

[FIXED] Stop subscription redelivery timer and signal handler on shutdown

---

stores/filestore.go
stores/filestore_msg_test.go

Doing some manual tests with removing the single .dat file for
a channel, I realized that in cluster mode, when the channel message
store was being emptied, the .idx file was not removed, which then
caused a problem since the info was added to the index file while
it should have been replaced.
Ensure that all files matching the messages files pattern are removed
during an Empty() call.

[FIXED] FileStore: Empty() should remove all message files (dat/idx)

---

server/clustering.go
server/clustering_test.go
server/conf.go
server/conf_test.go
server/snapshot.go
test/configs/test_parse.conf

When a node restore from a snapshot, it could be that the snapshot
information shows that a channel should have at least say messages
1 to 100. If the streaming store does not have these sequences,
the node is supposed to reconcile with the leader. However, if
all nodes are restarted and all have this issue, the cluster
would not be able to be restarted at all.
The new `cluster_proceed_on_restore_failure` will allow node(s)
to start.
Relates to #1010

[FIXED] Cluster: add flag to allow node to proceed on restore failure

---

logger/logger.go
logger/logger_test.go
server/server.go

Needed to pull NATS Server 2.1.4, and call the new SetSizeLimit() API

[ADDED] Ability to set logfile size limit

---

server/monitor.go
server/monitor_test.go

My use case for this feature is related to a kubernetes based deployment. We run nats in FT mode, which means that the monitor endpoints return useful information, or no information, depending on which node you make requests against. This feature will enable me to place some kind of reverse proxy in front of the nats nodes to proxy http requests on the monitor port to only the active node. 
With this PR in its current state, the only proxy i've found that i can configure to use appropriately is envoy. it seems most of the common reverse proxy solutions in use on k8s have varying levels of opinionatedness about how to configure health checks, and what constitutes "healthy". For instance, traefik considers any health check that returns a 2XX or 3XX to be healthy, and there's no way to alter …

[ADDED] Monitoring endpoint '/isFTActive' to evaluate whether the server is in FTActive mode

---

nats-streaming-server.go
server/service_windows.go

When starting as a Windows Service, we were creating a syslog to
possibly log the failure to start. But users running without
admin privileges would be unable to use the service since the
server would fail to create the event log entry.
So create the syslog only if explicit set (-syslog <bool> option)
or if no logfile has been specified.

[FIXED] Windows Service: do not force usage of syslog

---

nats-streaming-server.go
server/signal.go
server/signal_test.go

Previously, the reload signal was ignored. It will now be passed
on to the embedded NATS Server. If the streaming server remotely
connects to a NATS Server and a reload signal is received, the
streaming server will print a warning indicating that it works
only for NATS Server configuration and only if it is embedded.
Resolves #1030

[ADDED] Reload signal now accepted for the embedded NATS Server

---

.travis.yml
server/ft_test.go
server/monitor_test.go
server/partitions_test.go
server/server_delivery_test.go
server/server_run_test.go
stores/sqlstore_test.go

This may help speed up some Windows test in case "localhost" would
cause an attempt to connect to ::1 before failing back to 127.0.0.1.
Also update .travis.yml based on warnings displayed on the UI.

Change tests "localhost" to "127.0.0.1"

---

server/server_run_test.go
stores/filestore.go
stores/filestore_sub_test.go
stores/filestore_test.go

In some cases, the file name of the file unable to be recovered
due to an error reading the first 4 bytes of the file (to check
the file version) was not included in the error message, making
it difficult to debug which file was impacted.
Resolves #1034

[FIXED] Add filename in "unable to verify version" error

---

stores/filestore.go
stores/filestore_msg_test.go

Although for messages we were already adding the channel name, it is not enough and we should also include the actual file slice name (and .dat or .idx file). Missed that in PR #1035
Resolves #1034

Add message dat/idx file name for "unable to verify file version" error

---

go.mod
go.sum
vendor/go.etcd.io/bbolt/.travis.yml
vendor/go.etcd.io/bbolt/README.md
vendor/go.etcd.io/bbolt/bolt_386.go
vendor/go.etcd.io/bbolt/bolt_amd64.go
vendor/go.etcd.io/bbolt/bolt_arm.go
vendor/go.etcd.io/bbolt/bolt_arm64.go
vendor/go.etcd.io/bbolt/bolt_mips64x.go
vendor/go.etcd.io/bbolt/bolt_mipsx.go
vendor/go.etcd.io/bbolt/bolt_ppc.go
vendor/go.etcd.io/bbolt/bolt_ppc64.go
vendor/go.etcd.io/bbolt/bolt_ppc64le.go
vendor/go.etcd.io/bbolt/bolt_riscv64.go
vendor/go.etcd.io/bbolt/bolt_s390x.go
vendor/go.etcd.io/bbolt/bolt_unix_aix.go
vendor/go.etcd.io/bbolt/bucket.go
vendor/go.etcd.io/bbolt/cursor.go
vendor/go.etcd.io/bbolt/db.go
vendor/go.etcd.io/bbolt/freelist.go
vendor/go.etcd.io/bbolt/freelist_hmap.go
vendor/go.etcd.io/bbolt/go.mod
vendor/go.etcd.io/bbolt/go.sum
vendor/go.etcd.io/bbolt/node.go
vendor/go.etcd.io/bbolt/page.go
vendor/go.etcd.io/bbolt/tx.go
vendor/modules.txt

See https://github.com/etcd-io/bbolt/releases/tag/v1.3.4

[UPDATED] etcd/bbolt version to fix unsafe conversion found by Go 1.14

---

logger/logger.go
server/server.go
server/server_run_test.go

If NATS debug/trace is set but STAN debug/trace is not, after
a re-open signal, the server would stop tracing NATS debug/trace
statements.
Resolves #622

[FIXED] Signal reopen suppresses NATS debug/trace in some cases

---

.travis.yml
server/clustering_test.go
server/server_delivery_test.go

Update Travis go matrix to 1.14/1.13 instead of 1.13/1.12

Fixed possible test data races

---

server/server.go
server/server_delivery_test.go

Race was possibly sending a message to a closed subscription, which
would set the ack timer, which then server would report that it
is skipping delivery to this subscription due to timeout and showing
no clientID in the debug trace.
Resolves #1058

[FIXED] Don't send message to subscription that has just been closed

---

server/monitor.go

Minor fix for monitoring menu.
If we use nginx proxy for 8222 monitoring hosts. **http://host:81/stan/node1/streaming/** urls in menu  **http://host:81/ like http://host:81/streaming/channelsz** not  **http://host:81/stan/node1/streaming/channelsz**

[FIXED] Absolute url in streaming monitoring menu

---

stores/filestore.go
stores/filestore_msg_test.go

This could happen if recovery of an index does not have matching
information with the last message in corresponding ".dat" file.
In that case, the server wipes the index file and recreate it
based on the data file. However, the offset was not reset, which
means that the index file would contain wrong offsets.
Resolves #1086

[FIXED] FileStore: index file may be recreated with wrong offsets

---

server/clustering.go
server/raft_log.go
server/raft_log_test.go
stores/filestore_test.go

Was found by chance when causing backend boltdb store to throw
error when storing the raft log. The fact that a front-end log
cache was used and improperly caching logs that had failed to
be stored caused an issue for raft library. I have filed an
issue (and PR to fix) to the hashicorp/raft repo, but actually
decided to not use their LogCache since it can be easily added
to our raftLog implementation, reducing locking.

[FIXED] Clustering: possible panic on restart with "log not found"

---

server/server.go
server/server_test.go

If a random port is asked for in a call to `RunServerWithOpts`, return this port
in the `*server.Options argument`. Replaces the Port field with the OS assigned
port.
This PR also adds `ClientURL()` to `StanServer` as an alternate method of
fetching connection information.

[ADDED] ClientURL() API and expose an OS-assigned server port via the NATS server options 

---

stores/filestore.go
stores/filestore_msg_test.go

If an error occurs when trying to open an index file, the server
was incorrectly trying to unlock a data file that was possibly
not locked/opened. For instance in the case of expiring messages
from a slice that is not the current writing slice.
Resolves #1097

[FIXED] FileStore: possible panic when unable to open an index file

---

server/clustering_test.go
server/server.go

The clustering peers list is supposed to contain the list of peer
node ids. However, it happens that users make the mistake of listing
the node peer ids in the same string as such:
```
streaming {
cluster {
node_id: "a"
peers: ["a, b, c"]
}
}
```
The correct definition of `peers` should be:
```
peers: ["a", "b", "c"]
```
The server will now list the cluster known peers on startup and
will print a warning if a comma is detected in a peer name:
```
[INF] STREAM: peer 1: "a,b,c"
[WRN] STREAM: Peer name contains ',' make sure you provided an array of peer names, not a string with commas
```
Resolves #990

[IMPROVED] Clustering: Report possible misconfiguration of peers list

---

nats-streaming-server.go
server/clustering.go
server/clustering_test.go
server/conf.go
server/conf_test.go
server/server.go
test/configs/test_parse.conf

If option `allow_add_remove_node` in `streaming{cluster{}}` block
is enabled (or command line `--cluster_allow_add_remove_node`)
then the leader will listen to `_STAN.raft.<cluster id>.node.remove`
(and `...node.add`) to which an user can send a simple NATS request
with the value being the name of the node to add/remove.
If successful, the leader will return `+OK`, if not `-ERR` with
the error string explaining why it failed.
Note that removing a non-existent node will still return `+OK`.
If the leader receives a request to remove itself, it will work
but the process will then exit. It can be added back by sending
the request to the `..node.add` subject.
Note that this updates the RAFT configuration in the RAFT log but
does NOT change the configuration file. The admin will be responsible …

[ADDED] Clustering: ability to add/remove nodes at runtime

---

server/conf.go
server/conf_test.go
server/server.go
server/server_test.go
server/signal_test.go
test/configs/test_parse.conf

Abiltity to provide Username, Password or Token in the streaming
configuration block.
If the configuration is:
```
authorization {
users [
{ user: foo, password: bar}
]
}
streaming {
..
}
```
the server would fail to start unless user passes `-user foo -pass bar`
from the command line. But there was no way to pass those from the
configuration file. You can now configure this way:
```
streaming {
..
username: "foo"
password: "bar"
}
```
in order for the server to be able to start without the additional
`-user` and `-pass` command line parameters.
Also adding the `token` configuration option.

[ADDED] Authentication fields in streaming configuration block

---

server/conf.go
server/conf_test.go
server/server.go
server/server_test.go
test/configs/test_parse.conf

You can now configure the streaming server by providing a file
to the NKey seed. This will be used when creating the NATS connections
and when NKey authentication is required.
The file is read to get the seed in order to sign the nonce from
the NATS server. The seed is wiped out from memory after this
is done.
Resolves #1095

[ADDED] NKey support

---

server/server_test.go
util/sublist.go
util/sublist_test.go

With this fix, the channels bar and bar.> will be properly displayed.
```
[13010] 2020/10/12 18:08:35.531185 [INF] STREAM: -------- List of Channels --------
[13010] 2020/10/12 18:08:35.531188 [INF] STREAM: bar
[13010] 2020/10/12 18:08:35.531193 [INF] STREAM:  |-> Messages                    5
[13010] 2020/10/12 18:08:35.531196 [INF] STREAM: bar.>
[13010] 2020/10/12 18:08:35.531198 [INF] STREAM:  |-> Messages                   10
[13010] 2020/10/12 18:08:35.531200 [INF] STREAM: ----------------------------------
```
Resolves #1106

[FIXED] Display all configured channels

---

server/conf.go
server/server_test.go

It was impossible to set the file slice max bytes to 0. The default
64MB value would be used. Note that setting it in the configuration
file would work, only the command line would not.

[FIXED] Command line `-file_slice_max_bytes 0` was not working

---

nats-streaming-server.go
server/clustering_test.go
server/conf.go
server/conf_test.go
server/partitions_test.go
server/server.go
server/server_durable_test.go

When the subscription request for a durable subscription times out
or fail on the client side, but it was accepted in the server, then
if the application tries to restart the subscription request again
it will fail with a "duplicate durable subscription" error until
the connection is closed.
This new option allows the user to decide how the server should behave
when processing a duplicate durable subscription. If disabled, the
default, it behaves as described above, that is, it will reject
the second subscription request and return the "duplicate durable"
error.
If enabled, if the server detects that this is a duplicate, it will
close the active one and accept the new one. It is a suspend followed
by a resume.
From the client perspective, if this is done in the context of #1135,
then …

[ADDED] ReplaceDurable option

---

server/raft_transport.go
server/server.go
server/server_redelivery_test.go

During redelivery, a go routine gathers all pending messages under
a lock. However, the actual send of messages is done one by one
and by then, one of the message in the list of messages to redeliver
may have been acknowledged. So during the send, under the sub's lock,
we need to check that if a message marked as redelivered is no longer
in the pending list, it should not be sent to the client.
Also fixed an unrelated data race that was just found running tests.
Resolves #1138

[FIXED] Possible race causing ack'ed message to be redelivered

---

nats-streaming-server.go
server/conf.go
server/conf_test.go
stores/sqlstore.go
stores/sqlstore_test.go
test/configs/test_parse.conf

A new configuration `bulk_insert_limit` switches the server from
the current insertion of messages within a SQL transaction, to
an "INSERT INTO MESSAGES () VALUES (),(),..." which can speed up
performance by several folds.
The server still may perform regular insert within transaction
if the limit is deemed too low.
This new configuration parameter is not enabled by default. It
needs to be explicitly set, either in configuration file or
from command line `--sql_bulk_insert_limit <number here>`.
Resolves #1132

[IMPROVED] Bulk insert of messages

---

server/partitions.go
server/server.go
server/server_test.go

The NATS Streaming server uses NATS subscriptions to receive protocols
from the streaming clients. Except for the publish requests, these
internal subscriptions did not set the limits to "unlimited", which
could possibly lead to situation where some requests would be dropped
while other would not (if the server was slowing down to a point where
the NATS library would start to drop messages if the those internal
subscriptions queues were at the limit).
Of course, it is always possible that protocols be missed because
clients may be connected to a different server, and there could be
network issues, etc.. but this will reduce the risk.

[FIXED] Avoid possibly dropping client protocol requests

---

server/monitor.go
server/monitor_test.go

The detail of a client and channel will now have a `subs_count`
field that is the count of subscriptions, regardless if the
option to ask for subscriptions details is requested.
Even when the subscriptions details is requested, the count field
allows to quickly see how many subscriptions are present in the
array.

[ADDED] Subscriptions count in some monitoring endpoints

---

server/raft_log.go

An option for the `go.etcd.io/bbolt` library allows to set the type
of freelist merge functions, from the default `FreelistArrayType` to
an optional `FreelistMapType`. The doc explains:
```
Array which is simple but endures dramatic performance degradation
if database is large and framentation in freelist is common.
The alternative one is using hashmap, it is faster in almost all
circumstances.
```
However, although most of the options can be set through options
or by setting to the bolt.DB object itself, the `DB.FreelistType`
field was set after opening the bolt.DB object, which was too
late and would therefore always default to the "array" merge
function.
This PR now correctly creates bolt.Options and pass those to
the bolt.Open() call so that the options are properly used. …

[IMPROVED] Clustering: performance for fragmented RAFT logs

---

server/clustering.go
server/conf.go
server/conf_test.go
server/raft_log.go
server/raft_log_test.go
test/configs/test_parse.conf

Two new options can be configured:
`bolt_free_list_sync: <bool>` will cause free list to be sync'ed
on write. The default is `false` which means no sync.
You would enable this option if startup time matters more than
write performance because with this option, the DB does not need
to perform a full database re-sync.
`bolt_free_list_array: <bool>` switches to the "array" type of
free list, which may suffer for large databases with fragmented
free list. Up to v0.20.0 (included), this was the default but
PR #1155 made the "hashmap" free list type now the default.
This option allows you to revert to previous behavior.

[ADDED] Configuration parameters for RAFT's BoltDB store

---

server/server.go
server/server_req_test.go
server/server_sub_test.go
server/server_test.go

When the server detects that a client is not responding to heartbeats,
it closes it, however, this was done with a barrier that ensures
that all pending protocols on all internal subscriptions are first
processed.
In the case of this close (as opposed to processing a client close
request), this is not welcome because it may causes the server
to process lots of subscription requests that were sent by that
client - maybe in response to timeouts for a server already having
issues handling the load.
The server will now forcefully close the client (without the use
of the barrier) and the detection of an invalid client is done
sooner in the handling of the subscription request.
Also, the internal subscription for client subscription requests
has been reverted to be limited (with possibly …

[FIXED] Fail faster subscription requests for invalid clients

---

server/raft_transport.go
server/raft_transport_test.go
server/server_test.go

If there was a partial and what was in the pending buffer is less
than the size of the caller's buffer in Read(), we would get a
panic.

[FIXED] Clustering: possible panic with RAFT transport

---

server/raft_transport.go
server/raft_transport_test.go

This was introduced in v0.21.0 when I moved to sync subscriptions
and missed the fact that the pending limits do not apply to those
type of subscriptions.
Switching to async sub and adding buffers to a pending list.
These are consumed in the Read() call made by the RAFT library.

[FIXED] Clustering: possible slow consumer errors

---

server/raft_transport.go

When the RAFT connection is closed, if messages were being received
and the timing was wrong, it was possible to send to a closed go
channel, causing the panic.
Resolves #1183

[FIXED] Clustering: possible panic on shutdown

---

server/clustering_test.go
server/server.go
server/server_queue_test.go
server/server_redelivery_test.go

PR #997 introduced a map to keep track of how many times a message
was redelivered to a subscription (or a queue group). However, sequences
added to this map was never removed when the ACK was processed from
the subscription!

[FIXED] Subscription redelivery count map was not cleaned-up

---

server/monitor.go

This matches how the nats-server exposes the http monitoring endpoints as public
For people using this as a go package, allows for attaching to an existing http server instead of having to expose a duplicate http server endpoint
Discussed with @kozlovic over slack

[ADDED] Make http handlers public

---

server/clustering_test.go
server/snapshot.go

In some situations where a member has fallen behind and other
members left the group, a snapshot would have the lone member
with a lower last_sent, which could cause older messages to
be redelivered.

[FIXED] Clustering: snapshot queue group's last_sent

---

server/clustering_test.go
server/monitor_test.go
server/server.go

If a queue subscription is replacing a timed out one, the
leader would update its runtime version of the subscription's last_sent,
however, this would not be visible on the followers' monitoring
endpoint(s) until new messages were delivered.
Resolves #1189

[FIXED] last_sent may be 0 in monitor endpoint on followers

---

server/clustering_test.go
server/server.go

This is a regression introduced by PR #1213 which is in v0.23.0
(the latest release).
When a queue subscription left the group and its last_sent was the
same than the group's last_sent, the remaining queue member should
have its last_sent updated. To do that, the replication of a "sent"
event for this sequence was issued, which was wrong since it would
possibly add a pending on the remaining queue sub. Moreover, this
did not account for last_sent being 0, which with the aforementioned
behavior, a "sent" of sequence 0 would be replicated causing the
remaining queue sub to show a pending_count of 1.
The fix for both wrong pending_count and original last_sent issue
is to have all nodes (leader and followers) detect that when a
member is removed, if that member's last_sent value was the one …

[FIXED] Clustering: possible wrong pending count

---

server/clustering.go
server/clustering_test.go
server/server.go
server/snapshot.go

Suppose that a channel exists and there is a subscription for this
channel. A snapshot occurs, then later the subscription is closed.
After a while, the channel is removed.
If a server restarts and replays the snapshot and the rest of the
RAFT log, it will skip the recovery of the channel because it
would detect that the channel no longer exists, however, the
replay of the log would try to process the subscription close
and not find the channel.
We detect this case now and simply ignore the sub close protocol.
We also changed the error message, that still can be reported when
processing the request in the leader (before replication), from
"missing subject" to "unknown channel".
Resolves #1229

[FIXED] Clustering: don't report "sub close request missing subject" on replay

---

server/server.go
server/server_storefailures_test.go

If creation of a channel failed, this error was not always logged.

[FIXED] Log failure to create a channel

---

.goreleaser.yml
README.md
go.mod
go.sum
server/server.go

Release v0.24.0

---

server/monitor.go
server/monitor_test.go
server/server.go

If some monitoring endpoints were inspected during the start process
it could result in a panic due to a map read during a map set.
Resolves #1235

[FIXED] Possible panic on startup when monitoring endpoint inspected

---

server/server.go
server/server_redelivery_test.go

If the message redelivery callback fired and a client was marked
with failed heartbeat and the subscription is closed (likely
due to the server closing connection due to failed HBs), there
was a race that could cause a panic trying to reset a timer
that has been set to nil.

[FIXED] Possible panic on message redelivery

---

server/server.go

If the server times out a client while an application with
the same client ID just (re)connected and is about to resume
a durable consumer, a race could cause the subscription to
fail with an "unknown client ID" error if the replace_durable
option was set.
Resolves #1239

[FIXED] Race condition that could cause error on subscribe

---

server/conf.go
server/conf_test.go
stores/filestore.go
stores/filestore_test.go
test/configs/test_parse.conf

Reverted addition of record_size_limit (#1259, #1260, #1262)
But still address the memory usage caused by a corrupted data message
on recovery.
By using the expected record size from the index file, when checking
that the last message matches the index information, we would find
out that the index's stored message record size does not match the
record size in the ".dat" file and would not allocate the memory
to read the rest of the message.
The record_size_limit that was added to solve that issue would have
likely caused a lot of issues if mis-used.
Resolves #1255

[FIXED] Check expected record size before loading the payload

---

server/clustering_test.go
server/ft_test.go
server/server.go
server/server_delivery_test.go
server/server_storefailures_test.go
server/server_test.go
stores/common_msg_test.go
stores/filestore.go
stores/sqlstore.go
stores/store.go

A user reported that the server.dat was missing, which means that
the server did not recover channels (assuming that this was a
fresh start, without any state). This caused issues later on
since if an app publishes a message to an existing (non recovered)
channel, then messages would be added to the channel but with
a reset of the sequence.
The server will now warn of the situation, initialize the server
state and then recover the rest of the state (channels, etc..)
Resolves #1263

[FIXED] Recover channels even if server information not recovered

---

server/clustering.go
server/server.go
server/server_test.go

Due to the way channels are stored to persistent storage, the first spelling of a channel caused that channel to be persisted under that name.
If an application later publishes/subscribes to the same channel but with a different case (say first "Foo" then "foo"), the server would treat it as a new channel but would still store data in the first "Foo" channel, causing message sequences to be reset and inability to consume after a server restart.
From now on, the server will reject published messages or new subscriptions if it detects that a similar channel already exists with a different "case".
Resolves #1265

[CHANGED] Reject channels with different case (Foo vs foo)
