nats-io/nats-streaming-server

server/server.go, stores/common.go, stores/filestore.go, stores/memstore.go
We now only print the message once per subject.
=> [CHANGED] Logging when msgs limit is reached

stores/filestore.go, stores/filestore_test.go
Due to buffering, it was possible to flush on disk a partial record.
This increased the risk of failure to recover in case of crash after
a flush operation.
This change ensures that no partial record is stored in the buffer.
=> [FIXED] Buffered write strategy to reduce risk of partial writes

server/server.go
Debugf/Tracef check an atomic variable to see if the statement
should be logged or not. However, the cost of calling these
functions is significant due to memory allocations caused by
the formatting of the string being logged.
In places where speed matters, this is too much. Using server's
boolean (that capture the configured debug/trace options) and use
those to surround Debugf/Tracef calls improve performance by
limiting the calls to only when debug and/or trace are actually
enabled.
=> [IMPROVED] Performance by selectively calling Debugf/Tracef

server/server_test.go
=> Fix flapping test

server/server.go, server/server_test.go
If messages are published and server is shutdown, it was possible
that the server was unable to store the messages and would therefore
panic. Ensure that the storeIOLoop is done before closing the store.
Resolves #152
=> [FIXED] Possible panic on server shutdown

server/server.go, server/server_test.go
=> [FIXED] Durables were not properly removed on Unsubscribe

server/server.go
Publishing quickly to many subscribers could cause the connection from the NATS streaming server to the NATS server to error out with a slow consumer failure.  Based on machine specifications, the number of subscribers causing this error will vary.  
Adding a connection dedicated to sending to subscribers alleviates this, while providing roughly the same performance.  I experimented with additional connections (publish acks, receiving publishes), and surprisingly noticed a performance degradation in our benchmarks.
Because testing is dependent on OS/hardware resources, I did not add a test specific to this case.
On my macbook pro:
` go run stan-bench.go -ns 100 -np 1 -n 10000 -a foo`
would cause the NATS streaming server to error out with:
`[54777] 2016/10/26 20:42:31.180710 [INF] …
=> [ADDED] Connection for subscriber sends

server/server.go
Fixes a couple of typos in logging
=> Minor logging fixes

server/server.go, server/server_test.go
All internal subscribers now use a ChanSubscription and share the
same channel. Protocols are pulled-out and form a list that is
processed in a ioLoop go routine.
Resolves #195
=> [FIXED] Possible processing of protocols out-of-order

stores/filestore.go, stores/filestore_test.go
Use a go routine for all background/timer tasks. Use atomics for
checks to see if action need to be performed, reducing the need
for locking only on positive tests.
=> FileMsgStore reduce use of timers and lock contention

README.md, nats-streaming-server.go, scripts/cov.sh, server/conf.go, server/conf_test.go, stores/filestore.go, stores/filestore_test.go
The caching cannot be disabled but messages are evicted after
a short period of time.
Resolves #184
=> [UPDATED] File caching

server/server.go
Should have been done in PR #200
=> Removed unused subState field [ci skip]

README.md, nats-streaming-server.go
=> Fixed typo

README.md, nats-streaming-server.go, server/conf.go, server/conf_test.go, server/server.go, server/server_test.go, test/configs/test_parse.conf
Ability to configure heartbeat interval, timeout and number of
failed attempts.
Resolves #16
Resolves #54
=> [ADDED] Ability to configure server-to-client hearbeats

server/server.go, vendor/github.com/nats-io/gnatsd/server/const.go, vendor/github.com/nats-io/go-nats-streaming/stan.go, vendor/manifest
=> Release 0.3.6

stores/filestore.go, stores/filestore_test.go
This was caused by the tail of the list not being properly updated
when a cached message was looked-up (and moved to the end of the
list).
Added also some preventive code to make sure that expiration time in
the cache list is ever increasing.
Resolves #221
=> [FIXED] Possible crash during file store cache eviction

server/server.go, server/server_test.go
If a member of a queue group crashes, the server will not detect
that the client is gone until after the number of failed heartbeats.
In the meantime, messages may be assigned to that member. After
the AckWait period elapses, the server attempts to redeliver the
unacknowledged messages for that member. If there is at least
a failed heartbeat, the server would skip redelivery. This is
fine for regular subscribers, but in the case of a queue group,
it is likely that the message is actually redelivered to a different
member. So this PR skips the heartbeat check for a subscriber
that is part of a queue group, unless the group is down to that
single member.
Addresses #220
=> [UPDATED] Redelivery constraints for Queue Group

server/server.go, server/server_test.go
The server was not checking MaxInflight values from the SubscriptionRequest.
If value was 0 (or less), even if a message was available, the
server would try to send but because the number of pendind Acks (0)
would be >= of the MaxInflight (<=0), then no message would be sent
and subscriber would be flagged as stalled.
The server will now return an error if MaxInflight is <= 0.
Resolves #226
=> [FIXED] Message not sent and stalled subscriber if MaxInflight <= 0

server/server.go, server/server_test.go
The timer sending HB requests to the client was holding the client
lock for the duration of the request. Since the HBTimeout can
be quite large, this was problematic since it could block routines
in the server trying to lock the client object if the client was
disconnected and the timer was waiting for the HB reply.
Resolves #234
=> [FIXED] Client's lock held for ClientHBTimeout in checkClientHealth

server/server.go, server/server_test.go
Store's message next expiration time so that each message can
be redelivered at ack expiration time after last redelivery.
Resolves #237
=> [FIXED] Continous message redelivery not honoring sub's AckWait

server/server.go, server/server_test.go
When server attempts to deliver a message to a consumer, it calls
MsgProto.Marshal(). If the returned byte array is empty, the
server will now panic to indicate that the store implementation
is probably buggy.
Unrelated: fixed a flapping test
=> Check that store implementation does not return an empty MsgProto

.travis.yml, server/server_test.go, stores/common_test.go, stores/filestore.go, stores/filestore_test.go, stores/memstore.go
Also, moved the build and staticcheck/gosimple checks in `before_script` so that a failure there will stop the build process early.
=> Added gosimple

server/server.go, server/server_test.go
When a subscription request is received, the subscription is added
to the server and the response is sent back to the client before
starting to deliver messages to this subscription. However, in
the subscription request process, as soon as the subscription is
added but before the response is sent, if an application is sending
messages to the channel, it was possible that server would start
sending data to that subscription that had not yet fully initialized.
The issue was discovered with the node client:
https://github.com/nats-io/node-nats-streaming/issues/31
This was not affecting other Streaming client due to the use of
locking when processing the subscription request and processing
of incoming data.
=> [FIXED] Sending data before SubscriptionResponse

server/server.go
Processing of a new subscription request was followed by sending
available messages to this subscription. Since sub's MaxInflight
is set by user and can be quite big, it could delay the return
of this function, effectively delaying other new subscriptions
requests. This PR schedules the send of pending or avail messages
to another go routine.
=> [UPDATED] Schedule subscription start to go routine

server/server.go, server/server_test.go
In commit 5fd6384b127d35bd04e6eb408ff469dff395b1d6 where
an optional pool of subscriptions to handle subscribers' ACKs was
added, the prefix used was constant (_STAN.subacks.) which would
cause several NATS Streaming servers with different cluster IDs
to receive acks for other clusters. Nothing bad would happen in
that the inbox part of the subject would not map to subscribers,
but it generated unneeded traffic. The prefix now uses the cluster ID.
=> Fixed Acks Subscriptions pool to use cluster name in prefix

server/server.go, server/server_test.go
Issue caused by 5fd6384b127d35bd04e6eb408ff469dff395b1d6.
Code to extract ack inbox received from client needed to be moved
to subStore.LookupByAckInbox() since this is also used when
processing the close/unsubscribe requests.
=> Fixed AckInbox lookup when using Ack Subscriptions pool

server/ft.go, server/log.go, server/log_test.go, server/server.go, stores/filestore.go
Closes Issue #62 .
Changed prefix to STREAM from STAN.
Please double check unit test in server/log_test.go. It's a little weird due to the empty string case.
Also, to confirm, should we lowercase the first word in all log messages?
=> [ADDED] Cleanup Logging

server/ft_test.go
Attempt to reduce travis failures for some FT tests.
=> Fixed flapping FT tests

scripts/cross_compile.sh
=> [CHANGED] Do not include version in executable name [ci skip]

nats-streaming-server.go, server/server.go, server/signal.go, server/signal_test.go, server/signal_windows.go
Reworked the signal handling code to include support for the
log file rotation as done in NATS Server.
=> [ADDED] Signal handler for SIGUSR1 for log rotation

server/partitions_test.go
Increased request timeout for a partition test and ensure that
if server fails to start because route happens to be established
quicker than expected, the test does not fail.
=> Fixed flapping test

.travis.yml, Dockerfile, README.md, server/monitor.go, server/monitor_test.go, server/server.go, stores/common.go, stores/common_test.go, stores/delegate.go, stores/delegate_test.go, stores/filestore_test.go, stores/memstore_test.go, stores/store.go, vendor/github.com/nats-io/gnatsd/conf/lex.go, vendor/github.com/nats-io/gnatsd/server/monitor.go, vendor/github.com/nats-io/gnatsd/server/opts.go, vendor/github.com/nats-io/gnatsd/server/pse/pse_darwin.go, vendor/github.com/nats-io/gnatsd/server/route.go, vendor/github.com/nats-io/gnatsd/server/server.go, vendor/github.com/nats-io/go-nats/context.go, vendor/github.com/nats-io/go-nats/nats.go, vendor/github.com/nats-io/go-nats/netchan.go, vendor/github.com/nats-io/go-nats/parser.go, vendor/manifest
Added some endpoints for monitoring:
- server/
- store/
- clients/
- channels/
Resolves #116
=> [ADDED] Monitoring

server/server.go, server/server_test.go
A shadow queue subscriber is a record left in the store when the last
member of a queue group has left, but the state needs to be maintained.
There should be only one such shadow queue durable subscriber per
queue group per channel.
However, we got a case with a datastore that contained 2 such records.
Code inspection did not reveal how this could happen with current
code base, so it is suspected that this is the result of various
server upgrades with older datastores.
This change prevents the server from panic'ing and instead uses
the shadow subscriber with the highest lastSent value.
Resolves #322
=> [FIXED] Server panics when more than one shadow queue sub is recovered

server/server.go, server/server_test.go, stores/limits.go
In order for the server to properly own the given options,
implement a Clone() method.
=> Added Options.Clone()

scripts/cross_compile.sh
Similar to https://github.com/nats-io/gnatsd/issues/470
Resolves #334
=> [FIXED] Ensure executables are statically linked

scripts/cross_compile.sh
Similar to what was done for gnatsd.
=> [ADDED] ARMv6 and ARMv7 builds

README.md, server/server.go, server/server_test.go, stores/common.go, stores/common_test.go, stores/filestore.go, stores/filestore_test.go, stores/store.go
=> [CHANGED] SubStore.DeleteSub() is now returning an error

README.md, server/client.go, server/client_test.go, server/monitor.go, server/monitor_test.go, server/partitions_test.go, server/server.go, server/server_test.go, stores/bench_test.go, stores/common.go, stores/common_test.go, stores/filestore.go, stores/filestore_test.go, stores/memstore.go, stores/memstore_test.go, stores/store.go, util/lockfile_test.go
Some of channels and clients responsibilities have been moved
to the server, leading to removal of some of the Store APIs.
=> [CHANGED] Store interface refactoring

server/monitor_test.go, server/server_queue_test.go, server/server_test.go
Reduced some test code redundancy with the use of helpers functions.
=> Added helper functions for monitor tests

.travis.yml, misspell.sh, server/server_test.go
This tool combines staticcheck, gosimple and unused.
=> Adding megacheck tool

server/server.go, server/server_redelivery_test.go
- Ensure that unack'ed messages of each member are redelivered to
the same member, otherwise there is a risk that a message from
member 1 is redelivered to member 2, which adds it to the list
of unacknowledged, then when moving to member 2, that same message
may be redelivered to some other member, etc...
- Ensure that all unack'ed messages are attempted to be redelivered
before sending new messages.
Resolves #374
=> [FIXED] Queue redelivery on startup

vendor/github.com/nats-io/gnatsd/main.go, vendor/github.com/nats-io/gnatsd/server/opts.go, vendor/github.com/nats-io/gnatsd/server/sublist.go, vendor/manifest
Required for using changes made to ConfigureOptions()
=> Update vendor gnatsd

server/server_redelivery_test.go
Increased the AckWait to avoid redeliveries before the server
is restarted (which would otherwise cause this test to fail).
In the event the messages are redelivered before the server restart,
detect that situation and simply skip the test instead of failing
it.
=> Another attempt at fixing some flapping tests

README.md
Add reference to use of `?callback=` for endpoints and give an
example using jQuery.
=> [UPDATED] Readme on how to use JSONP for monitoring [ci skip]

server/conf_test.go, server/server_sub_test.go, stores/common_sub_test.go, stores/store.go, util/lockfile_unix.go, util/lockfile_win.go
fixed some typos I found looking through the code
=> fixed typos

.gitignore
I'd like to include Gogland and Intellij project files into .gitignore
=> added intellij to .gitignore

server/clustering.go, server/conf.go, server/conf_test.go, server/server.go, test/configs/test_parse.conf
Adds clustering support for config files and fixes a couple bugs related to clustering.
@kozlovic
=> Clustering config file support and bug fixes

server/server.go
If there are multiple channels, recovering a cluster could deadlock if
the servers recover the channels in different orders. This is because we
wait for a Raft leader to be elected and if we don't elect a leader in
30 seconds, we panic. To fix this, only wait for a leader when creating
the channel "online". If we're recovering, don't wait for the leader.
=> Fix clustered channel recovery

server/monitor.go, server/monitor_test.go
=> [ADDED] ClientID in monitor subscriptions

server/server.go
The raft.Apply().Error() is already ensuring that the command
is applied to the state machine, so there was no need for the Barrier
call in the contexts where it has been removed.
=> Removed unnecessary raft.Barrier calls

util/util_test.go
=> Try to address recent Travis test failures

stores/common_msg_test.go, stores/sqlstore.go, stores/sqlstore_test.go
This test has been failing often. Trying to add some debug
statements in case of failure
=> Add debug for MaxAge/FILE test

server/clustering_test.go, server/server.go
- We were using a timeout to enqueue raft.Apply() commands, while
we should really not (this could leave to an inconsistent state
between the raft and streaming logs).
- The replication functions were not really reporting to the clients
errors due to the processing of the command, only what the low
level raft failures.
Resolves #474
=> [FIXED] Server in cluster mode may Panic due to raft timeout

server/clustering.go, server/server.go, server/server_limits_test.go, server/server_storefailures_test.go, server/snapshot.go
Major rewrite of #469. There was an issue in clustering mode
if a channel deletion was replicated while a subscription was
removed.
Resolves #358
=> Fixed deletion of channels

server/clustering_test.go, server/snapshot.go
Batching code had a defect that would cause restore of messages
to be very slow.
=> [FIXED] Clustering: Restore messages from snapshot

README.md
=> [ADDED] Note about supported stores in clustering mode [ci skip]

README.md, server/server.go
=> [ADDED] Doc: how to configure NATS options when embedding Streaming server

server/conf.go, server/conf_test.go
=> fixed: support for declaring own node_id in peers

server/raft_transport.go
=> [FIXED] Possible slow consumer for raft transport subscriptions

server/server.go, server/server_clients_test.go
If several clients were stopped without calling Close() and are
then restarted, most would fail to reconnect.
Resolves #529
=> [FIXED] Inability to restart several clients at once

server/server.go, server/server_queue_test.go
If there were messages to deliver to a newly started queue subscription
and the queue subscription was closed quickly, say after receiving
the first message, the server would print the above error after
the sub's AckWait interval.
Resolves #535
=> [FIXED] "Unable to find queue subscriber" error on queue sub close

stores/filestore.go, stores/filestore_msg_test.go
If messages were stored with a gap in message sequence, it could
cause a panic when messages needed to be removed from the store.
This PR stores empty messages to fill the gap between the last
stored message and the new MsgStore.Store() call.
=> FileStore: support MsgStore.Store() with sequence gap

README.md
- Note about durable queue subscription saying that client ID is
not part of the queue name.
- Use of cluster_log_path when running NATS Streaming from Docker
so that RAFT state is restored, otherwise server will fail to
start.
Resolves #547
=> [UPDATED] Readme [ci skip]

server/clustering_test.go, server/raft_transport.go
This is a continuation of PR #551
=> Make use of raft transport timeout for nats.Conn.Flush calls

README.md, nats-streaming-server.go
Also reference was missing in configuration table
Resolves #574
=> [FIXED] Added SQL as avail store in help command [ci skip]

.travis.yml, Dockerfile, README.md, vendor/github.com/nats-io/gnatsd/conf/lex.go, vendor/github.com/nats-io/gnatsd/server/client.go, vendor/github.com/nats-io/gnatsd/server/const.go, vendor/github.com/nats-io/gnatsd/server/reload.go, vendor/github.com/nats-io/gnatsd/server/route.go, vendor/github.com/nats-io/gnatsd/server/server.go, vendor/github.com/nats-io/gnatsd/test/test.go, vendor/manifest
=> Prepare for release 0.10.0

stores/common_msg_test.go, stores/filestore_msg_test.go
=> Reset filestore cache TTL to proper value at end of test

server/server.go, server/server_clients_test.go
Also refactored a little bit processClientPings in server.go
=> Fixed TestPartitionsClientPings test

server/server.go, server/server_test.go, stores/sqlstore.go, stores/sqlstore_test.go
This is a regression introduced by #578.
Resolves #635
=> [FIXED] Ack possibly not processed if followed by Close

README.md
States that Channels Partitioning feature is incompatible with
Clustering mode.
Resolves #638
[ci skip]
=> [UPDATED] Documentation about Partitioning and Clustering

README.md
=> Prepare for release 0.11.0

.travis.yml, Dockerfile, server/partitions_test.go, server/raft_log.go, server/server_run_test.go, stores/sqlstore.go, test/sqlstore.go, vendor/github.com/nats-io/gnatsd/server/auth.go, vendor/github.com/nats-io/gnatsd/server/client.go, vendor/github.com/nats-io/gnatsd/server/opts.go, vendor/github.com/nats-io/gnatsd/server/sublist.go, vendor/github.com/nats-io/go-nats/context.go, vendor/github.com/nats-io/go-nats/enc.go, vendor/github.com/nats-io/go-nats/examples/nats-bench.go, vendor/github.com/nats-io/go-nats/nats.go, vendor/github.com/nats-io/go-nats/netchan.go, vendor/manifest
- Vendor gnatsd/go-nats
- Dockerfile and travis.yml's Go version to 1.11
- Some tests updates due to go 1.11 and some changes to go-nats
=> Some updates

server/clustering_test.go, server/server.go
The start position for subscriptions may be incorrect in clustering
mode.
Resolves #657
=> [FIXED] Clustering: Subscription start position may be incorrect

server/server.go, server/server_redelivery_test.go
Suppose the following example:
- send to member 1
- wait (no ack from 1)
- send to member 2
- wait
- receive an ack from member 1
- wait (no ack from 2)
- send to member 1 again
When server receives ack from member 1, although that message
is currently not assigned to this queue member, the server should
make an effort to remove this message from the ack pending list
of the member that has this message currently pending.
Resolves #653
=> [IMPROVED] Reduce queue redelivery in some situations

server/clustering.go, server/clustering_test.go, server/conf.go, server/conf_test.go, test/configs/test_parse.conf
Increased various timeouts. Introduced ability to configure them
through config file if need be.
=> [CHANGED] Clustering RAFT timeouts

stores/sqlstore.go, stores/sqlstore_test.go
There could be an issue with the SQLStore when server is restarted
and messages are expired during the recovery process. The first/last
sequence for a channel could be incorrect which would cause subscriptions
to possibly not receive messages since their last_sent could be higher
than the new last_seq for that channel.
Resolves #655
=> [FIXED] SQLStore: wrong first/last seq after recovery and expired msgs

Dockerfile, README.md, server/clustering.go, server/clustering_test.go, server/server.go
=> Prepare for new release

README.md
=> Little typo on readme file and add a note on FT mode

stores/cryptostore.go
=> Removed debug print statement and put back actual code!

server/server.go, server/server_redelivery_test.go
Forces the redelivery of messages when assigned to a queue member,
This will help speed up redelivery when messages were assigned
to a queue member that has crashed (but server does not know
about it yet). This works only if the queue member is restarted
with the same clientID. For queue members using generated UIDs
for the client ID, messages assigned to such crashed member will
not be redelivered until the server detects the connection as
dead and reassigns its undelivered messages to another member.
Resolves #725
=> [IMPROVED] Queue redelivery when members crash and are restarted

stores/sqlstore.go
=> Fixed staticcheck report

Dockerfile, README.md
=> Release v0.12.0

.travis.yml, scripts/cov.sh, server/clustering_test.go, server/server.go, server/server_limits_test.go, server/server_storefailures_test.go
There was a race between the decision of deleting a channel and
the processing of a subscription on that channel that could cause
the server to deadlock in clustering mode.
=> [FIXED] Clustering: possible deadlock on channel deletion

server/server.go, server/server_run_test.go
Removed the options tracing that had no value and redact the
username/password/token from the url that is displayed in the log
when reconnecting to a NATS Server.
Resolves #746
=> [FIXED] Don't expose user/password in log when reconnecting to NATS

.travis.yml, Dockerfile, server/server.go
Also adds the proper git commit for the embedded NATS Server.
Resolves #755
=> [ADDED] GitCommit to NATS Streaming Server

Dockerfile, README.md, server/server.go
=> Release v0.12.2

README.md, nats-streaming-server.go
=> [FIXED] -help: indicate that cluster_peers is comma separated list

server/clustering_test.go, server/monitor.go, server/server.go, server/snapshot.go
Ensure that we don't reset a channel's store first sequence to
1 in some situations.
Resolves #795
=> [FIXED] Clustering: possible subscription stall

Dockerfile, README.md, server/server.go
=> Release 0.14.0

server/clustering_test.go, server/server.go
There was a wrong assumption that calling raft.Apply() without
waiting on the future result would be non blocking. This is not
the case. RAFT internally uses go channels and there may be cases
when a receiver on a channel is busy and so sending to that channel
will block.
This is what was happening. RAFT would invoke the streaming server
code to apply the replication of a connection close. In this process
we try to remove subscriptions of that connection. This requires
the subStore lock. However, another go routine may be holding that
lock (and possibly subscription's lock, queue state, etc..) and
at the same time call raft.Apply() to replicate an aggregate of
subscription's sent/ack operations. In some cases this would actually
block, causing the deadlock.
Reworked handling of …
=> [FIXED] Clustering: possible deadlock on sub/conn close

README.md
=> Release 0.14.1

server/server.go
PR #749 addressed a possible deadlock when a channel was being
deleted while subscription request was processed.
But this fix had a window that could have caused a channel that
should have been scheduled for deletion to not be, leaving the
channel around more than needed.
(This was discovered with recent failure of existing test:
--- FAIL: TestClusteringDeadlockOnChannelDelete (6.31s)
clustering_test.go:4237: Deadlock likely!!!)
=> [FIXED] Channel may not be deleted when it should

server/clustering_test.go, server/server.go, server/server_test.go
There was still an issue with replication of sent/ack when sub/conn
was being closed.
Resolves #821
=> [FIXED] Clustering: issue when sub/conn closed while msgs published

README.md
=> Small Typo in README

server/clustering_test.go, server/server.go, server/snapshot.go
PR #835 fixed an issue with restoreMsgsFromSnapshot when there
were unavailable messages (expired or removed due to limits).
However, the implementation was not optimized when lots of
messages are no longer available. Also, it would not be backward
compatible with older servers.
This change detects if two servers are 0.14.1+ and can then
send the first available sequence if the leader does not find
the requested message.
With this code change, a follower that requests messages to a
leader that is of previous version will handle unavailable
messages in an optimized way. It will first send few requests
starting at the next sequence but then will try to do a binary
search but first ask the leader for the last message on its
range. If this message is not found, then that means all messages
in …
=> Optimize restoreMsgsFromSnapshot and make it backward compatible

README.md, server/raft_log_test.go, server/server.go, server/server_durable_test.go, server/server_limits_test.go, util/lockfile_test.go
- update tests based on staticcheck reports
- update version info in README outputs
=> Prepare for release 0.14.3

Dockerfile, go.mod, go.sum, vendor/github.com/nats-io/nats-server/v2/server/const.go, vendor/modules.txt
=> Update to NATS Server official v2.0.0 tag

README.md, server/server.go
=> Release v0.15.1

README.md
=> Added missing file_read_buffer_size in README [ci skip]

stores/cryptostore_test.go, stores/filestore.go, stores/filestore_test.go, stores/raftstore_test.go
The original implementation was having a central timer routine
that would go through the list of channels (interface) and cast
them to FileMsgStore and FileSubStore to invoke the stores' autoSync()
functions.
However, with stores that wrap a FileStore instance (such as RAFT or
Crypto store), that would cause a panic since the casting would fail.
Alternative fix would have been for FileStore to maintain a separate
map of actual File[Msg/Sub]Store, but I chose instead to move the
call to autoSync() into the Msg/Sub stores themselves.
Relates to #882
=> Fixed implementation of FileStore auto-sync feature

go.mod, go.sum, vendor/github.com/hashicorp/raft/CHANGELOG.md, vendor/github.com/hashicorp/raft/Makefile, vendor/github.com/hashicorp/raft/README.md, vendor/github.com/hashicorp/raft/api.go, vendor/github.com/hashicorp/raft/config.go, vendor/github.com/hashicorp/raft/configuration.go, vendor/github.com/hashicorp/raft/fsm.go, vendor/github.com/hashicorp/raft/go.mod, vendor/github.com/hashicorp/raft/go.sum, vendor/github.com/hashicorp/raft/log.go, vendor/github.com/hashicorp/raft/raft.go, vendor/github.com/hashicorp/raft/replication.go, vendor/github.com/hashicorp/raft/testing.go, vendor/modules.txt
This was due to RAFT library. Updated the go.mod to their new
version v1.1.1 that includes the fix.
Resolves #884
=> [FIXED] Panic when running 32-bit release

server/clustering.go, server/clustering_test.go
When RAFT logging is enabled, starting 0.15.0, it looks like
the raft logging is a bit off. Something similar to this:
```
[32605] 2019/07/25 13:46:57.787222 [WRN] STREAM:  raft: Heartbeat timeout from "" reached, starting election
[32605] 2019/07/25 13:46:57.787270 [INF] STREAM:  raft: Node at test-cluster.a.test-cluster [Candidate] entering Candidate state in term 2
[32605] 2019/07/25 13:46:59.792967 [WRN] STREAM:  raft: Election timeout reached, restarting election
[32605] 2019/07/25 13:46:59.793034 [INF] STREAM:  raft: Node at test-cluster.a.test-cluster [Candidate] entering Candidate state in term 3
[32605] 2019/07/25 13:46:59.793060 [ERR] STREAM: ] raft: Failed to make RequestVote RPC to {Voter b test-cluster.b.test-cluster}: nats: timeout
```
Notice the extra white space between …
=> [FIXED] Raft logging

stores/sqlstore.go, stores/sqlstore_test.go
This could happen only when the active server is shutdown, as opposed
to when it crashes.
Resolves #901
=> [FIXED] SQLStore: tick column of StoreLock table may not be updated

README.md, go.mod, go.sum, nats-streaming-server.go, server/server_test.go, stores/pqdeadlines/pqdeadlines.go, stores/sqlstore.go, stores/sqlstore_test.go
This will allow the drop of stale DB connections.
Resolves #906
=> [ADDED] Read/Write timeouts to Postgres driver

server/server.go, server/server_queue_test.go
When a queue member was removed and it had unacknowledged messages,
those were reassigned to other queue members. We would then invoke
the redelivery routine to reset the ack timer, but this would have
the consequence of possibly doing redeliveries at that time.
Instead, reset the queue members that had reassigned messages to
fire shortly.
=> Avoid redelivery right when removing a queue member

server/server.go, server/server_run_test.go
This notice is added:
- In standalone: after the store is recovered
- In FT: when the server becomes active and after recovering the store
- In cluster mode: after performing actions when becoming leader
Resolves #917
=> [ADDED] "Streaming Server is ready" log statement

server/server.go, server/server_test.go
Original issue was addressed in PR #247, but unfortunately the fix
did not take into account durable subscriptions. If a durable
subscription is restarted, the subscription object is in memory
and would have the flag "initialized" already set to true, which
would not prevent published messages at the time of the subscription
request processing to allow messages to be sent prior to the
subscription response.
Resolves #930
=> [FIXED] Ensure Subscription response sent prior to messages

server/conf.go, server/conf_test.go, server/server.go, test/configs/test_parse.conf
Updates based off @david-gurley's PR (https://github.com/nats-io/nats-streaming-server/pull/927)
=> [ADDED] Credentials option to connect to external NATS Server

server/clustering_test.go, server/server_test.go, stores/common_test.go, test/test.go, util/util_test.go
=> Fixed some staticcheck reports

README.md
=> [FIXED] Slack invite URL [ci skip]

server/clustering_test.go, server/server.go
See #993 for details.
Resolves #993
=> [FIXED] Clustering: "stalled" status not properly updated on leader election

.goreleaser.yml, .travis.yml, Dockerfile, README.md, server/server.go
=> Release 0.17.0

MAINTAINERS.md
adding R.I. Pienaar as core-maintainer
=> Update Maintainer.md [ci skip]

.travis.yml, server/clustering_test.go, server/server_run_test.go, stores/filestore_sub_test.go
=> Add Windows to Travis CI

logger/logger.go, server/signal.go, server/signal_test.go
=> [FIXED] NATS debug/trace may not be honored after reload+reopen signals

.travis.yml
=> Update Go release in Travis

.goreleaser.yml
=> Added `.tar.gz` to release downloads

.travis.yml, README.md, server/server.go, server/server_run_test.go
=> [FIXED] Fatal error on startup not logged to log file

server/server_durable_test.go, server/server_test.go, stores/common_test.go
=> Fix tests for staticcheck SA5011

server/server.go
We were using a NUID for subjects such as `_STAN.pub.<nuid>.>`
when running in standalone mode without channel partitioning.
In all other cases, we used the cluster ID in place of the nuid.
This change will make use of the cluster ID in all cases. This
will apply only to new deployment, meaning that existing stores
with NUID in the subjects will still be used.
=> [CHANGED] User cluster ID as part of internal subscriptions

go.mod, go.sum, stores/sqlstore.go, stores/sqlstore_test.go, vendor/github.com/lib/pq/.gitignore, vendor/github.com/lib/pq/.travis.yml, vendor/github.com/lib/pq/array.go, vendor/github.com/lib/pq/conn.go, vendor/github.com/lib/pq/conn_go18.go, vendor/github.com/lib/pq/copy.go, vendor/github.com/lib/pq/error.go, vendor/modules.txt
=> Updated Postgres deps and made some update to bulk insert code

README.md, dependencies.md, server/server.go
=> Release v0.20.0

server/server.go
A new connection is new to handle server-to-client sending of heatbeats.
This could cause contention with the "general" connection that was
previously used since this connection is used for handling other
protocols.
In situations where there are lots of clients and the heartbeat settings
are low, this could cause contention.
Also fixed a bug that could have caused a panic should the server handle
a PING from the client while that client had just been closed.
=> [FIXED] Reduce contention with client heartbeats and prevent panic

server/raft_log.go, stores/cryptostore.go
raftLog is a wrapper to bolt's DB database. I think that we
can remove some of the raftLog's locking since bolt's DB itself
will ensure locking.
I am not expecting much of a performance boost with this PR, but
it has been observed contention between GetLog and StoreLogs in
some cases, so that may help.
=> [IMPROVED] Reduce use of locking in raftlog.go

server/server.go, server/server_sub_test.go
This will allow the client library to issue a sub close request
on a subscribe timeout. Since the library won't have the AckInbox,
it will send a sub close request with Inbox and if the server
fails the lookup with ack inbox, falls back to lookup by inbox.
=> [FIXED] Support closing of subscriptions with inbox instead of ack inbox

README.md, server/server.go
=> Release v0.21.0

server/monitor.go, server/monitor_test.go, server/server_redelivery_test.go
=> [FIXED] Added missing cluster node ID in serverz endpoint

README.md, server/server.go
=> Release v0.21.1

server/raft_transport.go
Changes in v0.21.0 made heavy use of time.After() in a select that
caused an unacceptable memory growth.
Replaced with creating a timer once and using stop/reset kept
the memory usage in check.
Resolves #1176
=> [FIXED] Clustering: memory growth

.travis.yml, README.md, server/server.go
=> Release v0.21.2

server/clustering_test.go
This test verifies that if a queue member is stalled, new messages
are delivered as expected to the non stalled queue member
=> Add clustering queue sub stalled test

.goreleaser.yml, README.md, server/server.go
=> Release v0.22.0

server/clustering_test.go, server/server.go
I have added a test with a sleep in performRedeliveryOnStartup
that would demonstrate the issue when this function was started
as a go routine. The sleep/test is a bit useless with new code
since this is invoked in place, but will catch the issue if
in the future this function is again invoked as a go routine.
=> [FIXED] Possible redelivery from node that lost leadership

server/raft_transport.go, server/raft_transport_test.go
Some races could leave dialed/accepted connections to be added
to the list (and not closed) on some tests shutdown, which could
cause some other tests to fail because of unexpected reconnects.
=> Ensure RAFT connection are closed if transport is closed

stores/sqlstore.go, stores/sqlstore_test.go
With message expiration, after some sequence of events, it could
be that a subscription's last_sent sequence would be higher
than the store's last_seq.
=> [FIXED] SQL: sub last_sent could end-up higher than store last_seq

.goreleaser.yml, README.md, go.mod, go.sum, server/server.go
=> Release v0.24.1

.goreleaser.yml, README.md, go.mod, go.sum, server/server.go
=> Release v0.24.5

.goreleaser.yml, README.md, go.mod, go.sum, server/server.go
=> Release v0.24.6

stores/filestore.go, stores/filestore_test.go
In case of memory corruption, it is possible that the record size
is way greater than it should, which would cause the server to
create a buffer of the wrong size in the attempt to read the
record. This new option will limit how big the buffer needed
to read the record from disk can be.
Resolves #1255
=> [ADDED] FileStore: RecordSizeLimit to limit single record read size

server/conf.go, server/conf_test.go, test/configs/test_parse.conf
=> Added parsing of record_size_limit new option

stores/filestore.go, stores/filestore_test.go
Related to PR #1259
Resolves https://github.com/nats-io/nats-streaming-server/issues/1261
=> Add RecordSizeLimit to AllOptions

server/clustering_test.go, server/ft_test.go, server/server_delivery_test.go, server/server_queue_test.go, server/server_storefailures_test.go, server/server_sub_test.go
=> Fixed how SQL tests are run in the server package

.goreleaser.yml, README.md, server/server.go
=> Release v0.25.0

.goreleaser.yml, README.md, server/server.go
=> Release v0.25.6
